// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: shopping_cart/proto/shopping_cart.proto

package proto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CartItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                 // DB ID of the row in cart_items
	MenuItemId    string                 `protobuf:"bytes,2,opt,name=menuItemId,proto3" json:"menuItemId,omitempty"` // ID from Restaurant Service
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      int32                  `protobuf:"varint,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartItem) Reset() {
	*x = CartItem{}
	mi := &file_shopping_cart_proto_shopping_cart_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartItem) ProtoMessage() {}

func (x *CartItem) ProtoReflect() protoreflect.Message {
	mi := &file_shopping_cart_proto_shopping_cart_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartItem.ProtoReflect.Descriptor instead.
func (*CartItem) Descriptor() ([]byte, []int) {
	return file_shopping_cart_proto_shopping_cart_proto_rawDescGZIP(), []int{0}
}

func (x *CartItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CartItem) GetMenuItemId() string {
	if x != nil {
		return x.MenuItemId
	}
	return ""
}

func (x *CartItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CartItem) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CartItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type CartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // Cart ID
	UserId        string                 `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	RestaurantId  string                 `protobuf:"bytes,3,opt,name=restaurantId,proto3" json:"restaurantId,omitempty"`
	Items         []*CartItem            `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	TotalPrice    float64                `protobuf:"fixed64,5,opt,name=totalPrice,proto3" json:"totalPrice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartResponse) Reset() {
	*x = CartResponse{}
	mi := &file_shopping_cart_proto_shopping_cart_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartResponse) ProtoMessage() {}

func (x *CartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shopping_cart_proto_shopping_cart_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartResponse.ProtoReflect.Descriptor instead.
func (*CartResponse) Descriptor() ([]byte, []int) {
	return file_shopping_cart_proto_shopping_cart_proto_rawDescGZIP(), []int{1}
}

func (x *CartResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CartResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CartResponse) GetRestaurantId() string {
	if x != nil {
		return x.RestaurantId
	}
	return ""
}

func (x *CartResponse) GetItems() []*CartItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CartResponse) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

type GetCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"` // Extracted from Token
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCartRequest) Reset() {
	*x = GetCartRequest{}
	mi := &file_shopping_cart_proto_shopping_cart_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCartRequest) ProtoMessage() {}

func (x *GetCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shopping_cart_proto_shopping_cart_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCartRequest.ProtoReflect.Descriptor instead.
func (*GetCartRequest) Descriptor() ([]byte, []int) {
	return file_shopping_cart_proto_shopping_cart_proto_rawDescGZIP(), []int{2}
}

func (x *GetCartRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type AddItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	RestaurantId  string                 `protobuf:"bytes,2,opt,name=restaurantId,proto3" json:"restaurantId,omitempty"`
	MenuItemId    string                 `protobuf:"bytes,3,opt,name=menuItemId,proto3" json:"menuItemId,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Price         float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      int32                  `protobuf:"varint,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddItemRequest) Reset() {
	*x = AddItemRequest{}
	mi := &file_shopping_cart_proto_shopping_cart_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddItemRequest) ProtoMessage() {}

func (x *AddItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shopping_cart_proto_shopping_cart_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddItemRequest.ProtoReflect.Descriptor instead.
func (*AddItemRequest) Descriptor() ([]byte, []int) {
	return file_shopping_cart_proto_shopping_cart_proto_rawDescGZIP(), []int{3}
}

func (x *AddItemRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddItemRequest) GetRestaurantId() string {
	if x != nil {
		return x.RestaurantId
	}
	return ""
}

func (x *AddItemRequest) GetMenuItemId() string {
	if x != nil {
		return x.MenuItemId
	}
	return ""
}

func (x *AddItemRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddItemRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *AddItemRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type UpdateQuantityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	ItemId        string                 `protobuf:"bytes,2,opt,name=itemId,proto3" json:"itemId,omitempty"` // cart_item ID
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateQuantityRequest) Reset() {
	*x = UpdateQuantityRequest{}
	mi := &file_shopping_cart_proto_shopping_cart_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateQuantityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateQuantityRequest) ProtoMessage() {}

func (x *UpdateQuantityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shopping_cart_proto_shopping_cart_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateQuantityRequest.ProtoReflect.Descriptor instead.
func (*UpdateQuantityRequest) Descriptor() ([]byte, []int) {
	return file_shopping_cart_proto_shopping_cart_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateQuantityRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateQuantityRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *UpdateQuantityRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type RemoveItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	ItemId        string                 `protobuf:"bytes,2,opt,name=itemId,proto3" json:"itemId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveItemRequest) Reset() {
	*x = RemoveItemRequest{}
	mi := &file_shopping_cart_proto_shopping_cart_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveItemRequest) ProtoMessage() {}

func (x *RemoveItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shopping_cart_proto_shopping_cart_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveItemRequest.ProtoReflect.Descriptor instead.
func (*RemoveItemRequest) Descriptor() ([]byte, []int) {
	return file_shopping_cart_proto_shopping_cart_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveItemRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RemoveItemRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

type ClearCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearCartRequest) Reset() {
	*x = ClearCartRequest{}
	mi := &file_shopping_cart_proto_shopping_cart_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearCartRequest) ProtoMessage() {}

func (x *ClearCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shopping_cart_proto_shopping_cart_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearCartRequest.ProtoReflect.Descriptor instead.
func (*ClearCartRequest) Descriptor() ([]byte, []int) {
	return file_shopping_cart_proto_shopping_cart_proto_rawDescGZIP(), []int{6}
}

func (x *ClearCartRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_shopping_cart_proto_shopping_cart_proto protoreflect.FileDescriptor

const file_shopping_cart_proto_shopping_cart_proto_rawDesc = "" +
	"\n" +
	"'shopping_cart/proto/shopping_cart.proto\x12\rshopping_cart\x1a\x1cgoogle/api/annotations.proto\"\x80\x01\n" +
	"\bCartItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1e\n" +
	"\n" +
	"menuItemId\x18\x02 \x01(\tR\n" +
	"menuItemId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\x05R\bquantity\"\xa9\x01\n" +
	"\fCartResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\tR\x06userId\x12\"\n" +
	"\frestaurantId\x18\x03 \x01(\tR\frestaurantId\x12-\n" +
	"\x05items\x18\x04 \x03(\v2\x17.shopping_cart.CartItemR\x05items\x12\x1e\n" +
	"\n" +
	"totalPrice\x18\x05 \x01(\x01R\n" +
	"totalPrice\"(\n" +
	"\x0eGetCartRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\"\xb2\x01\n" +
	"\x0eAddItemRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\"\n" +
	"\frestaurantId\x18\x02 \x01(\tR\frestaurantId\x12\x1e\n" +
	"\n" +
	"menuItemId\x18\x03 \x01(\tR\n" +
	"menuItemId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12\x1a\n" +
	"\bquantity\x18\x06 \x01(\x05R\bquantity\"c\n" +
	"\x15UpdateQuantityRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06itemId\x18\x02 \x01(\tR\x06itemId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\"C\n" +
	"\x11RemoveItemRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06itemId\x18\x02 \x01(\tR\x06itemId\"*\n" +
	"\x10ClearCartRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId2\x80\x04\n" +
	"\x13ShoppingCartService\x12T\n" +
	"\aGetCart\x12\x1d.shopping_cart.GetCartRequest\x1a\x1b.shopping_cart.CartResponse\"\r\x82\xd3\xe4\x93\x02\a\x12\x05/cart\x12]\n" +
	"\aAddItem\x12\x1d.shopping_cart.AddItemRequest\x1a\x1b.shopping_cart.CartResponse\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/cart/items\x12o\n" +
	"\x12UpdateItemQuantity\x12$.shopping_cart.UpdateQuantityRequest\x1a\x1b.shopping_cart.CartResponse\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\x1a\v/cart/items\x12i\n" +
	"\n" +
	"RemoveItem\x12 .shopping_cart.RemoveItemRequest\x1a\x1b.shopping_cart.CartResponse\"\x1c\x82\xd3\xe4\x93\x02\x16*\x14/cart/items/{itemId}\x12X\n" +
	"\tClearCart\x12\x1f.shopping_cart.ClearCartRequest\x1a\x1b.shopping_cart.CartResponse\"\r\x82\xd3\xe4\x93\x02\a*\x05/cartB\x1cZ\x1acommon/shopping_cart/protob\x06proto3"

var (
	file_shopping_cart_proto_shopping_cart_proto_rawDescOnce sync.Once
	file_shopping_cart_proto_shopping_cart_proto_rawDescData []byte
)

func file_shopping_cart_proto_shopping_cart_proto_rawDescGZIP() []byte {
	file_shopping_cart_proto_shopping_cart_proto_rawDescOnce.Do(func() {
		file_shopping_cart_proto_shopping_cart_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shopping_cart_proto_shopping_cart_proto_rawDesc), len(file_shopping_cart_proto_shopping_cart_proto_rawDesc)))
	})
	return file_shopping_cart_proto_shopping_cart_proto_rawDescData
}

var file_shopping_cart_proto_shopping_cart_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_shopping_cart_proto_shopping_cart_proto_goTypes = []any{
	(*CartItem)(nil),              // 0: shopping_cart.CartItem
	(*CartResponse)(nil),          // 1: shopping_cart.CartResponse
	(*GetCartRequest)(nil),        // 2: shopping_cart.GetCartRequest
	(*AddItemRequest)(nil),        // 3: shopping_cart.AddItemRequest
	(*UpdateQuantityRequest)(nil), // 4: shopping_cart.UpdateQuantityRequest
	(*RemoveItemRequest)(nil),     // 5: shopping_cart.RemoveItemRequest
	(*ClearCartRequest)(nil),      // 6: shopping_cart.ClearCartRequest
}
var file_shopping_cart_proto_shopping_cart_proto_depIdxs = []int32{
	0, // 0: shopping_cart.CartResponse.items:type_name -> shopping_cart.CartItem
	2, // 1: shopping_cart.ShoppingCartService.GetCart:input_type -> shopping_cart.GetCartRequest
	3, // 2: shopping_cart.ShoppingCartService.AddItem:input_type -> shopping_cart.AddItemRequest
	4, // 3: shopping_cart.ShoppingCartService.UpdateItemQuantity:input_type -> shopping_cart.UpdateQuantityRequest
	5, // 4: shopping_cart.ShoppingCartService.RemoveItem:input_type -> shopping_cart.RemoveItemRequest
	6, // 5: shopping_cart.ShoppingCartService.ClearCart:input_type -> shopping_cart.ClearCartRequest
	1, // 6: shopping_cart.ShoppingCartService.GetCart:output_type -> shopping_cart.CartResponse
	1, // 7: shopping_cart.ShoppingCartService.AddItem:output_type -> shopping_cart.CartResponse
	1, // 8: shopping_cart.ShoppingCartService.UpdateItemQuantity:output_type -> shopping_cart.CartResponse
	1, // 9: shopping_cart.ShoppingCartService.RemoveItem:output_type -> shopping_cart.CartResponse
	1, // 10: shopping_cart.ShoppingCartService.ClearCart:output_type -> shopping_cart.CartResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_shopping_cart_proto_shopping_cart_proto_init() }
func file_shopping_cart_proto_shopping_cart_proto_init() {
	if File_shopping_cart_proto_shopping_cart_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shopping_cart_proto_shopping_cart_proto_rawDesc), len(file_shopping_cart_proto_shopping_cart_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shopping_cart_proto_shopping_cart_proto_goTypes,
		DependencyIndexes: file_shopping_cart_proto_shopping_cart_proto_depIdxs,
		MessageInfos:      file_shopping_cart_proto_shopping_cart_proto_msgTypes,
	}.Build()
	File_shopping_cart_proto_shopping_cart_proto = out.File
	file_shopping_cart_proto_shopping_cart_proto_goTypes = nil
	file_shopping_cart_proto_shopping_cart_proto_depIdxs = nil
}
