// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: restaurant/proto/restaurant.proto

package proto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Used inside the Menu message
type MenuItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuItem) Reset() {
	*x = MenuItem{}
	mi := &file_restaurant_proto_restaurant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuItem) ProtoMessage() {}

func (x *MenuItem) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_proto_restaurant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuItem.ProtoReflect.Descriptor instead.
func (*MenuItem) Descriptor() ([]byte, []int) {
	return file_restaurant_proto_restaurant_proto_rawDescGZIP(), []int{0}
}

func (x *MenuItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MenuItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MenuItem) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

// --- THIS WAS MISSING ---
type MenuItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuItemResponse) Reset() {
	*x = MenuItemResponse{}
	mi := &file_restaurant_proto_restaurant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuItemResponse) ProtoMessage() {}

func (x *MenuItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_proto_restaurant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuItemResponse.ProtoReflect.Descriptor instead.
func (*MenuItemResponse) Descriptor() ([]byte, []int) {
	return file_restaurant_proto_restaurant_proto_rawDescGZIP(), []int{1}
}

func (x *MenuItemResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MenuItemResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MenuItemResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type Menu struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Items         []*MenuItem            `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Menu) Reset() {
	*x = Menu{}
	mi := &file_restaurant_proto_restaurant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Menu) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Menu) ProtoMessage() {}

func (x *Menu) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_proto_restaurant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Menu.ProtoReflect.Descriptor instead.
func (*Menu) Descriptor() ([]byte, []int) {
	return file_restaurant_proto_restaurant_proto_rawDescGZIP(), []int{2}
}

func (x *Menu) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Menu) GetItems() []*MenuItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type RestaurantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	IsOpen        bool                   `protobuf:"varint,4,opt,name=isOpen,proto3" json:"isOpen,omitempty"`
	Menu          *Menu                  `protobuf:"bytes,5,opt,name=menu,proto3" json:"menu,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestaurantResponse) Reset() {
	*x = RestaurantResponse{}
	mi := &file_restaurant_proto_restaurant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestaurantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestaurantResponse) ProtoMessage() {}

func (x *RestaurantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_proto_restaurant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestaurantResponse.ProtoReflect.Descriptor instead.
func (*RestaurantResponse) Descriptor() ([]byte, []int) {
	return file_restaurant_proto_restaurant_proto_rawDescGZIP(), []int{3}
}

func (x *RestaurantResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RestaurantResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RestaurantResponse) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *RestaurantResponse) GetIsOpen() bool {
	if x != nil {
		return x.IsOpen
	}
	return false
}

func (x *RestaurantResponse) GetMenu() *Menu {
	if x != nil {
		return x.Menu
	}
	return nil
}

type CreateRestaurantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRestaurantRequest) Reset() {
	*x = CreateRestaurantRequest{}
	mi := &file_restaurant_proto_restaurant_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRestaurantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRestaurantRequest) ProtoMessage() {}

func (x *CreateRestaurantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_proto_restaurant_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRestaurantRequest.ProtoReflect.Descriptor instead.
func (*CreateRestaurantRequest) Descriptor() ([]byte, []int) {
	return file_restaurant_proto_restaurant_proto_rawDescGZIP(), []int{4}
}

func (x *CreateRestaurantRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRestaurantRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type UpdateStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IsOpen        bool                   `protobuf:"varint,2,opt,name=isOpen,proto3" json:"isOpen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStatusRequest) Reset() {
	*x = UpdateStatusRequest{}
	mi := &file_restaurant_proto_restaurant_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusRequest) ProtoMessage() {}

func (x *UpdateStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_proto_restaurant_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateStatusRequest) Descriptor() ([]byte, []int) {
	return file_restaurant_proto_restaurant_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateStatusRequest) GetIsOpen() bool {
	if x != nil {
		return x.IsOpen
	}
	return false
}

type AddMenuItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RestaurantId  string                 `protobuf:"bytes,1,opt,name=restaurantId,proto3" json:"restaurantId,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMenuItemRequest) Reset() {
	*x = AddMenuItemRequest{}
	mi := &file_restaurant_proto_restaurant_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMenuItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMenuItemRequest) ProtoMessage() {}

func (x *AddMenuItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_proto_restaurant_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMenuItemRequest.ProtoReflect.Descriptor instead.
func (*AddMenuItemRequest) Descriptor() ([]byte, []int) {
	return file_restaurant_proto_restaurant_proto_rawDescGZIP(), []int{6}
}

func (x *AddMenuItemRequest) GetRestaurantId() string {
	if x != nil {
		return x.RestaurantId
	}
	return ""
}

func (x *AddMenuItemRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddMenuItemRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type GetAllRestaurantsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllRestaurantsRequest) Reset() {
	*x = GetAllRestaurantsRequest{}
	mi := &file_restaurant_proto_restaurant_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllRestaurantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRestaurantsRequest) ProtoMessage() {}

func (x *GetAllRestaurantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_proto_restaurant_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRestaurantsRequest.ProtoReflect.Descriptor instead.
func (*GetAllRestaurantsRequest) Descriptor() ([]byte, []int) {
	return file_restaurant_proto_restaurant_proto_rawDescGZIP(), []int{7}
}

type GetAllRestaurantsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Restaurants   []*RestaurantResponse  `protobuf:"bytes,1,rep,name=restaurants,proto3" json:"restaurants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllRestaurantsResponse) Reset() {
	*x = GetAllRestaurantsResponse{}
	mi := &file_restaurant_proto_restaurant_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllRestaurantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRestaurantsResponse) ProtoMessage() {}

func (x *GetAllRestaurantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_proto_restaurant_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRestaurantsResponse.ProtoReflect.Descriptor instead.
func (*GetAllRestaurantsResponse) Descriptor() ([]byte, []int) {
	return file_restaurant_proto_restaurant_proto_rawDescGZIP(), []int{8}
}

func (x *GetAllRestaurantsResponse) GetRestaurants() []*RestaurantResponse {
	if x != nil {
		return x.Restaurants
	}
	return nil
}

type GetRestaurantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRestaurantRequest) Reset() {
	*x = GetRestaurantRequest{}
	mi := &file_restaurant_proto_restaurant_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRestaurantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRestaurantRequest) ProtoMessage() {}

func (x *GetRestaurantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_proto_restaurant_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRestaurantRequest.ProtoReflect.Descriptor instead.
func (*GetRestaurantRequest) Descriptor() ([]byte, []int) {
	return file_restaurant_proto_restaurant_proto_rawDescGZIP(), []int{9}
}

func (x *GetRestaurantRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_restaurant_proto_restaurant_proto protoreflect.FileDescriptor

const file_restaurant_proto_restaurant_proto_rawDesc = "" +
	"\n" +
	"!restaurant/proto/restaurant.proto\x12\n" +
	"restaurant\x1a\x1cgoogle/api/annotations.proto\"D\n" +
	"\bMenuItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\"L\n" +
	"\x10MenuItemResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\"B\n" +
	"\x04Menu\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12*\n" +
	"\x05items\x18\x02 \x03(\v2\x14.restaurant.MenuItemR\x05items\"\x92\x01\n" +
	"\x12RestaurantResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x16\n" +
	"\x06isOpen\x18\x04 \x01(\bR\x06isOpen\x12$\n" +
	"\x04menu\x18\x05 \x01(\v2\x10.restaurant.MenuR\x04menu\"I\n" +
	"\x17CreateRestaurantRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\"=\n" +
	"\x13UpdateStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06isOpen\x18\x02 \x01(\bR\x06isOpen\"b\n" +
	"\x12AddMenuItemRequest\x12\"\n" +
	"\frestaurantId\x18\x01 \x01(\tR\frestaurantId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\"\x1a\n" +
	"\x18GetAllRestaurantsRequest\"]\n" +
	"\x19GetAllRestaurantsResponse\x12@\n" +
	"\vrestaurants\x18\x01 \x03(\v2\x1e.restaurant.RestaurantResponseR\vrestaurants\"&\n" +
	"\x14GetRestaurantRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2\xd6\x04\n" +
	"\x11RestaurantService\x12o\n" +
	"\x10CreateRestaurant\x12#.restaurant.CreateRestaurantRequest\x1a\x1e.restaurant.RestaurantResponse\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/restaurant\x12s\n" +
	"\fUpdateStatus\x12\x1f.restaurant.UpdateStatusRequest\x1a\x1e.restaurant.RestaurantResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\x1a\x17/restaurant/{id}/status\x12w\n" +
	"\vAddMenuItem\x12\x1e.restaurant.AddMenuItemRequest\x1a\x1c.restaurant.MenuItemResponse\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/restaurant/{restaurantId}/menu\x12u\n" +
	"\x11GetAllRestaurants\x12$.restaurant.GetAllRestaurantsRequest\x1a%.restaurant.GetAllRestaurantsResponse\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/restaurant\x12k\n" +
	"\rGetRestaurant\x12 .restaurant.GetRestaurantRequest\x1a\x1e.restaurant.RestaurantResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/restaurant/{id}B\x1aZ\x18/COMMON/restaurant/protob\x06proto3"

var (
	file_restaurant_proto_restaurant_proto_rawDescOnce sync.Once
	file_restaurant_proto_restaurant_proto_rawDescData []byte
)

func file_restaurant_proto_restaurant_proto_rawDescGZIP() []byte {
	file_restaurant_proto_restaurant_proto_rawDescOnce.Do(func() {
		file_restaurant_proto_restaurant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_restaurant_proto_restaurant_proto_rawDesc), len(file_restaurant_proto_restaurant_proto_rawDesc)))
	})
	return file_restaurant_proto_restaurant_proto_rawDescData
}

var file_restaurant_proto_restaurant_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_restaurant_proto_restaurant_proto_goTypes = []any{
	(*MenuItem)(nil),                  // 0: restaurant.MenuItem
	(*MenuItemResponse)(nil),          // 1: restaurant.MenuItemResponse
	(*Menu)(nil),                      // 2: restaurant.Menu
	(*RestaurantResponse)(nil),        // 3: restaurant.RestaurantResponse
	(*CreateRestaurantRequest)(nil),   // 4: restaurant.CreateRestaurantRequest
	(*UpdateStatusRequest)(nil),       // 5: restaurant.UpdateStatusRequest
	(*AddMenuItemRequest)(nil),        // 6: restaurant.AddMenuItemRequest
	(*GetAllRestaurantsRequest)(nil),  // 7: restaurant.GetAllRestaurantsRequest
	(*GetAllRestaurantsResponse)(nil), // 8: restaurant.GetAllRestaurantsResponse
	(*GetRestaurantRequest)(nil),      // 9: restaurant.GetRestaurantRequest
}
var file_restaurant_proto_restaurant_proto_depIdxs = []int32{
	0, // 0: restaurant.Menu.items:type_name -> restaurant.MenuItem
	2, // 1: restaurant.RestaurantResponse.menu:type_name -> restaurant.Menu
	3, // 2: restaurant.GetAllRestaurantsResponse.restaurants:type_name -> restaurant.RestaurantResponse
	4, // 3: restaurant.RestaurantService.CreateRestaurant:input_type -> restaurant.CreateRestaurantRequest
	5, // 4: restaurant.RestaurantService.UpdateStatus:input_type -> restaurant.UpdateStatusRequest
	6, // 5: restaurant.RestaurantService.AddMenuItem:input_type -> restaurant.AddMenuItemRequest
	7, // 6: restaurant.RestaurantService.GetAllRestaurants:input_type -> restaurant.GetAllRestaurantsRequest
	9, // 7: restaurant.RestaurantService.GetRestaurant:input_type -> restaurant.GetRestaurantRequest
	3, // 8: restaurant.RestaurantService.CreateRestaurant:output_type -> restaurant.RestaurantResponse
	3, // 9: restaurant.RestaurantService.UpdateStatus:output_type -> restaurant.RestaurantResponse
	1, // 10: restaurant.RestaurantService.AddMenuItem:output_type -> restaurant.MenuItemResponse
	8, // 11: restaurant.RestaurantService.GetAllRestaurants:output_type -> restaurant.GetAllRestaurantsResponse
	3, // 12: restaurant.RestaurantService.GetRestaurant:output_type -> restaurant.RestaurantResponse
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_restaurant_proto_restaurant_proto_init() }
func file_restaurant_proto_restaurant_proto_init() {
	if File_restaurant_proto_restaurant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_restaurant_proto_restaurant_proto_rawDesc), len(file_restaurant_proto_restaurant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_restaurant_proto_restaurant_proto_goTypes,
		DependencyIndexes: file_restaurant_proto_restaurant_proto_depIdxs,
		MessageInfos:      file_restaurant_proto_restaurant_proto_msgTypes,
	}.Build()
	File_restaurant_proto_restaurant_proto = out.File
	file_restaurant_proto_restaurant_proto_goTypes = nil
	file_restaurant_proto_restaurant_proto_depIdxs = nil
}
