// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: order/proto/order.proto

package proto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderStatus int32

const (
	OrderStatus_PENDING          OrderStatus = 0
	OrderStatus_PREPARING        OrderStatus = 1
	OrderStatus_READY_FOR_PICKUP OrderStatus = 2
	OrderStatus_IN_DELIVERY      OrderStatus = 3
	OrderStatus_DELIVERED        OrderStatus = 4
	OrderStatus_CANCELLED        OrderStatus = 5
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "PENDING",
		1: "PREPARING",
		2: "READY_FOR_PICKUP",
		3: "IN_DELIVERY",
		4: "DELIVERED",
		5: "CANCELLED",
	}
	OrderStatus_value = map[string]int32{
		"PENDING":          0,
		"PREPARING":        1,
		"READY_FOR_PICKUP": 2,
		"IN_DELIVERY":      3,
		"DELIVERED":        4,
		"CANCELLED":        5,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_order_proto_order_proto_enumTypes[0].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_order_proto_order_proto_enumTypes[0]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_order_proto_order_proto_rawDescGZIP(), []int{0}
}

type OrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Price         float64                `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_order_proto_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_order_proto_order_proto_rawDescGZIP(), []int{0}
}

func (x *OrderItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrderItem) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type OrderResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RestaurantId          string                 `protobuf:"bytes,2,opt,name=restaurantId,proto3" json:"restaurantId,omitempty"`
	CustomerId            string                 `protobuf:"bytes,3,opt,name=customerId,proto3" json:"customerId,omitempty"`
	DeliveryPersonId      string                 `protobuf:"bytes,4,opt,name=deliveryPersonId,proto3" json:"deliveryPersonId,omitempty"`
	Status                string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	DeliveryAddress       string                 `protobuf:"bytes,6,opt,name=deliveryAddress,proto3" json:"deliveryAddress,omitempty"`
	ItemsTotal            float64                `protobuf:"fixed64,7,opt,name=itemsTotal,proto3" json:"itemsTotal,omitempty"`
	DeliveryFee           float64                `protobuf:"fixed64,8,opt,name=deliveryFee,proto3" json:"deliveryFee,omitempty"`
	AppFee                float64                `protobuf:"fixed64,9,opt,name=appFee,proto3" json:"appFee,omitempty"`
	SmallOrderFee         float64                `protobuf:"fixed64,10,opt,name=smallOrderFee,proto3" json:"smallOrderFee,omitempty"`
	TotalPrice            float64                `protobuf:"fixed64,11,opt,name=totalPrice,proto3" json:"totalPrice,omitempty"`
	Items                 []*OrderItem           `protobuf:"bytes,12,rep,name=items,proto3" json:"items,omitempty"`
	CreatedAt             string                 `protobuf:"bytes,13,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	IsPriority            bool                   `protobuf:"varint,14,opt,name=isPriority,proto3" json:"isPriority,omitempty"`
	EstimatedDeliveryTime string                 `protobuf:"bytes,15,opt,name=estimatedDeliveryTime,proto3" json:"estimatedDeliveryTime,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *OrderResponse) Reset() {
	*x = OrderResponse{}
	mi := &file_order_proto_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderResponse) ProtoMessage() {}

func (x *OrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderResponse.ProtoReflect.Descriptor instead.
func (*OrderResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_order_proto_rawDescGZIP(), []int{1}
}

func (x *OrderResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrderResponse) GetRestaurantId() string {
	if x != nil {
		return x.RestaurantId
	}
	return ""
}

func (x *OrderResponse) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *OrderResponse) GetDeliveryPersonId() string {
	if x != nil {
		return x.DeliveryPersonId
	}
	return ""
}

func (x *OrderResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OrderResponse) GetDeliveryAddress() string {
	if x != nil {
		return x.DeliveryAddress
	}
	return ""
}

func (x *OrderResponse) GetItemsTotal() float64 {
	if x != nil {
		return x.ItemsTotal
	}
	return 0
}

func (x *OrderResponse) GetDeliveryFee() float64 {
	if x != nil {
		return x.DeliveryFee
	}
	return 0
}

func (x *OrderResponse) GetAppFee() float64 {
	if x != nil {
		return x.AppFee
	}
	return 0
}

func (x *OrderResponse) GetSmallOrderFee() float64 {
	if x != nil {
		return x.SmallOrderFee
	}
	return 0
}

func (x *OrderResponse) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *OrderResponse) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *OrderResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *OrderResponse) GetIsPriority() bool {
	if x != nil {
		return x.IsPriority
	}
	return false
}

func (x *OrderResponse) GetEstimatedDeliveryTime() string {
	if x != nil {
		return x.EstimatedDeliveryTime
	}
	return ""
}

type CreateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	CustomAddress string                 `protobuf:"bytes,2,opt,name=customAddress,proto3" json:"customAddress,omitempty"`
	CustomLat     float64                `protobuf:"fixed64,3,opt,name=customLat,proto3" json:"customLat,omitempty"`
	CustomLon     float64                `protobuf:"fixed64,4,opt,name=customLon,proto3" json:"customLon,omitempty"`
	IsPriority    bool                   `protobuf:"varint,5,opt,name=isPriority,proto3" json:"isPriority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_order_proto_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_order_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOrderRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateOrderRequest) GetCustomAddress() string {
	if x != nil {
		return x.CustomAddress
	}
	return ""
}

func (x *CreateOrderRequest) GetCustomLat() float64 {
	if x != nil {
		return x.CustomLat
	}
	return 0
}

func (x *CreateOrderRequest) GetCustomLon() float64 {
	if x != nil {
		return x.CustomLon
	}
	return 0
}

func (x *CreateOrderRequest) GetIsPriority() bool {
	if x != nil {
		return x.IsPriority
	}
	return false
}

type GetOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrdersRequest) Reset() {
	*x = GetOrdersRequest{}
	mi := &file_order_proto_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrdersRequest) ProtoMessage() {}

func (x *GetOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrdersRequest.ProtoReflect.Descriptor instead.
func (*GetOrdersRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_order_proto_rawDescGZIP(), []int{3}
}

func (x *GetOrdersRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetOrdersRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type GetOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*OrderResponse       `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrdersResponse) Reset() {
	*x = GetOrdersResponse{}
	mi := &file_order_proto_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrdersResponse) ProtoMessage() {}

func (x *GetOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrdersResponse.ProtoReflect.Descriptor instead.
func (*GetOrdersResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_order_proto_rawDescGZIP(), []int{4}
}

func (x *GetOrdersResponse) GetOrders() []*OrderResponse {
	if x != nil {
		return x.Orders
	}
	return nil
}

type UpdateStatusRequest struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	OrderId                  string                 `protobuf:"bytes,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	Status                   OrderStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=order.OrderStatus" json:"status,omitempty"`
	DeliveryPersonId         string                 `protobuf:"bytes,3,opt,name=deliveryPersonId,proto3" json:"deliveryPersonId,omitempty"`
	EstimatedDeliveryMinutes int32                  `protobuf:"varint,4,opt,name=estimatedDeliveryMinutes,proto3" json:"estimatedDeliveryMinutes,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *UpdateStatusRequest) Reset() {
	*x = UpdateStatusRequest{}
	mi := &file_order_proto_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusRequest) ProtoMessage() {}

func (x *UpdateStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateStatusRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_order_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateStatusRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *UpdateStatusRequest) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_PENDING
}

func (x *UpdateStatusRequest) GetDeliveryPersonId() string {
	if x != nil {
		return x.DeliveryPersonId
	}
	return ""
}

func (x *UpdateStatusRequest) GetEstimatedDeliveryMinutes() int32 {
	if x != nil {
		return x.EstimatedDeliveryMinutes
	}
	return 0
}

type GetRestaurantOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RestaurantId  string                 `protobuf:"bytes,1,opt,name=restaurantId,proto3" json:"restaurantId,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRestaurantOrdersRequest) Reset() {
	*x = GetRestaurantOrdersRequest{}
	mi := &file_order_proto_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRestaurantOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRestaurantOrdersRequest) ProtoMessage() {}

func (x *GetRestaurantOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRestaurantOrdersRequest.ProtoReflect.Descriptor instead.
func (*GetRestaurantOrdersRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_order_proto_rawDescGZIP(), []int{6}
}

func (x *GetRestaurantOrdersRequest) GetRestaurantId() string {
	if x != nil {
		return x.RestaurantId
	}
	return ""
}

func (x *GetRestaurantOrdersRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_order_proto_order_proto protoreflect.FileDescriptor

const file_order_proto_order_proto_rawDesc = "" +
	"\n" +
	"\x17order/proto/order.proto\x12\x05order\x1a\x1cgoogle/api/annotations.proto\"Q\n" +
	"\tOrderItem\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x01R\x05price\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\"\x8d\x04\n" +
	"\rOrderResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\"\n" +
	"\frestaurantId\x18\x02 \x01(\tR\frestaurantId\x12\x1e\n" +
	"\n" +
	"customerId\x18\x03 \x01(\tR\n" +
	"customerId\x12*\n" +
	"\x10deliveryPersonId\x18\x04 \x01(\tR\x10deliveryPersonId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12(\n" +
	"\x0fdeliveryAddress\x18\x06 \x01(\tR\x0fdeliveryAddress\x12\x1e\n" +
	"\n" +
	"itemsTotal\x18\a \x01(\x01R\n" +
	"itemsTotal\x12 \n" +
	"\vdeliveryFee\x18\b \x01(\x01R\vdeliveryFee\x12\x16\n" +
	"\x06appFee\x18\t \x01(\x01R\x06appFee\x12$\n" +
	"\rsmallOrderFee\x18\n" +
	" \x01(\x01R\rsmallOrderFee\x12\x1e\n" +
	"\n" +
	"totalPrice\x18\v \x01(\x01R\n" +
	"totalPrice\x12&\n" +
	"\x05items\x18\f \x03(\v2\x10.order.OrderItemR\x05items\x12\x1c\n" +
	"\tcreatedAt\x18\r \x01(\tR\tcreatedAt\x12\x1e\n" +
	"\n" +
	"isPriority\x18\x0e \x01(\bR\n" +
	"isPriority\x124\n" +
	"\x15estimatedDeliveryTime\x18\x0f \x01(\tR\x15estimatedDeliveryTime\"\xae\x01\n" +
	"\x12CreateOrderRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12$\n" +
	"\rcustomAddress\x18\x02 \x01(\tR\rcustomAddress\x12\x1c\n" +
	"\tcustomLat\x18\x03 \x01(\x01R\tcustomLat\x12\x1c\n" +
	"\tcustomLon\x18\x04 \x01(\x01R\tcustomLon\x12\x1e\n" +
	"\n" +
	"isPriority\x18\x05 \x01(\bR\n" +
	"isPriority\">\n" +
	"\x10GetOrdersRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\"A\n" +
	"\x11GetOrdersResponse\x12,\n" +
	"\x06orders\x18\x01 \x03(\v2\x14.order.OrderResponseR\x06orders\"\xc3\x01\n" +
	"\x13UpdateStatusRequest\x12\x18\n" +
	"\aorderId\x18\x01 \x01(\tR\aorderId\x12*\n" +
	"\x06status\x18\x02 \x01(\x0e2\x12.order.OrderStatusR\x06status\x12*\n" +
	"\x10deliveryPersonId\x18\x03 \x01(\tR\x10deliveryPersonId\x12:\n" +
	"\x18estimatedDeliveryMinutes\x18\x04 \x01(\x05R\x18estimatedDeliveryMinutes\"X\n" +
	"\x1aGetRestaurantOrdersRequest\x12\"\n" +
	"\frestaurantId\x18\x01 \x01(\tR\frestaurantId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status*n\n" +
	"\vOrderStatus\x12\v\n" +
	"\aPENDING\x10\x00\x12\r\n" +
	"\tPREPARING\x10\x01\x12\x14\n" +
	"\x10READY_FOR_PICKUP\x10\x02\x12\x0f\n" +
	"\vIN_DELIVERY\x10\x03\x12\r\n" +
	"\tDELIVERED\x10\x04\x12\r\n" +
	"\tCANCELLED\x10\x052\xa0\x03\n" +
	"\fOrderService\x12R\n" +
	"\vCreateOrder\x12\x19.order.CreateOrderRequest\x1a\x14.order.OrderResponse\"\x12\x82\xd3\xe4\x93\x02\f:\x01*\"\a/orders\x12Q\n" +
	"\vGetMyOrders\x12\x17.order.GetOrdersRequest\x1a\x18.order.GetOrdersResponse\"\x0f\x82\xd3\xe4\x93\x02\t\x12\a/orders\x12j\n" +
	"\x11UpdateOrderStatus\x12\x1a.order.UpdateStatusRequest\x1a\x14.order.OrderResponse\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\x1a\x18/orders/{orderId}/status\x12}\n" +
	"\x13GetRestaurantOrders\x12!.order.GetRestaurantOrdersRequest\x1a\x18.order.GetOrdersResponse\")\x82\xd3\xe4\x93\x02#\x12!/orders/restaurant/{restaurantId}B\x14Z\x12common/order/protob\x06proto3"

var (
	file_order_proto_order_proto_rawDescOnce sync.Once
	file_order_proto_order_proto_rawDescData []byte
)

func file_order_proto_order_proto_rawDescGZIP() []byte {
	file_order_proto_order_proto_rawDescOnce.Do(func() {
		file_order_proto_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_proto_order_proto_rawDesc), len(file_order_proto_order_proto_rawDesc)))
	})
	return file_order_proto_order_proto_rawDescData
}

var file_order_proto_order_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_order_proto_order_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_order_proto_order_proto_goTypes = []any{
	(OrderStatus)(0),                   // 0: order.OrderStatus
	(*OrderItem)(nil),                  // 1: order.OrderItem
	(*OrderResponse)(nil),              // 2: order.OrderResponse
	(*CreateOrderRequest)(nil),         // 3: order.CreateOrderRequest
	(*GetOrdersRequest)(nil),           // 4: order.GetOrdersRequest
	(*GetOrdersResponse)(nil),          // 5: order.GetOrdersResponse
	(*UpdateStatusRequest)(nil),        // 6: order.UpdateStatusRequest
	(*GetRestaurantOrdersRequest)(nil), // 7: order.GetRestaurantOrdersRequest
}
var file_order_proto_order_proto_depIdxs = []int32{
	1, // 0: order.OrderResponse.items:type_name -> order.OrderItem
	2, // 1: order.GetOrdersResponse.orders:type_name -> order.OrderResponse
	0, // 2: order.UpdateStatusRequest.status:type_name -> order.OrderStatus
	3, // 3: order.OrderService.CreateOrder:input_type -> order.CreateOrderRequest
	4, // 4: order.OrderService.GetMyOrders:input_type -> order.GetOrdersRequest
	6, // 5: order.OrderService.UpdateOrderStatus:input_type -> order.UpdateStatusRequest
	7, // 6: order.OrderService.GetRestaurantOrders:input_type -> order.GetRestaurantOrdersRequest
	2, // 7: order.OrderService.CreateOrder:output_type -> order.OrderResponse
	5, // 8: order.OrderService.GetMyOrders:output_type -> order.GetOrdersResponse
	2, // 9: order.OrderService.UpdateOrderStatus:output_type -> order.OrderResponse
	5, // 10: order.OrderService.GetRestaurantOrders:output_type -> order.GetOrdersResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_order_proto_order_proto_init() }
func file_order_proto_order_proto_init() {
	if File_order_proto_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_proto_order_proto_rawDesc), len(file_order_proto_order_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_proto_order_proto_goTypes,
		DependencyIndexes: file_order_proto_order_proto_depIdxs,
		EnumInfos:         file_order_proto_order_proto_enumTypes,
		MessageInfos:      file_order_proto_order_proto_msgTypes,
	}.Build()
	File_order_proto_order_proto = out.File
	file_order_proto_order_proto_goTypes = nil
	file_order_proto_order_proto_depIdxs = nil
}
