syntax = "proto3";

package order;

option go_package = "common/order/proto";

import "google/api/annotations.proto";

service OrderService {
  // 1. Create Order (The Orchestrator)
  rpc CreateOrder (CreateOrderRequest) returns (OrderResponse) {
    option (google.api.http) = {
      post: "/orders"
      body: "*"
    };
  }

  // 2. Get My Orders
  rpc GetMyOrders (GetOrdersRequest) returns (GetOrdersResponse) {
    option (google.api.http) = {
      get: "/orders"
    };
  }

  // 3. Update Status (For Restaurant/Delivery)
  rpc UpdateOrderStatus (UpdateStatusRequest) returns (OrderResponse) {
    option (google.api.http) = {
      put: "/orders/{orderId}/status"
      body: "*"
    };
  }

  rpc GetRestaurantOrders (GetRestaurantOrdersRequest) returns (GetOrdersResponse) {
    option (google.api.http) = {
      get: "/orders/restaurant/{restaurantId}"
    };
  }

  rpc BidForOrder (BidRequest) returns (BidResponse) {
    option (google.api.http) = {
      post: "/orders/{orderId}/bid"
      body: "*"
    };
  }
  
  // To show drivers available jobs
  rpc GetAvailableOrders (GetAvailableOrdersRequest) returns (GetOrdersResponse) {
    option (google.api.http) = {
      get: "/orders/available"
    };
  }

  rpc GetMyActiveJob (GetOrdersRequest) returns (OrderResponse) {
    option (google.api.http) = {
      get: "/orders/active"
    };
  }
}

enum OrderStatus {
  PENDING = 0;
  PREPARING = 1;
  READY_FOR_PICKUP = 2;
  IN_DELIVERY = 3;
  DELIVERED = 4;
  CANCELLED = 5;
}

message OrderItem {
  string name = 1;
  double price = 2; 
  int32 quantity = 3;
}

message OrderResponse {
  string id = 1;
  string restaurantId = 2;
  string customerId = 3;
  string deliveryPersonId = 4; 
  
  string status = 5;
  string deliveryAddress = 6;
  
  double itemsTotal = 7;
  double deliveryFee = 8;
  double appFee = 9;
  double smallOrderFee = 10;
  double totalPrice = 11;

  repeated OrderItem items = 12;
  string createdAt = 13;
  bool isPriority = 14;

  int32 preparingFoodDeliveryTime = 15;
  int32 deliveryDurationTime = 16;
}

message CreateOrderRequest {
  string userId = 1; 
  string customAddress = 2;
  double customLat = 3;
  double customLon = 4;
  bool isPriority = 5; 
}

message GetOrdersRequest {
  string userId = 1;
  string role = 2; 
}

message GetOrdersResponse {
  repeated OrderResponse orders = 1;
}

message UpdateStatusRequest {
  string orderId = 1;
  OrderStatus status = 2;
  string deliveryPersonId = 3; 
  int32 foodReadyAt = 4;
}

message GetRestaurantOrdersRequest {
  string restaurantId = 1;
  string status = 2; 
}

message BidRequest {
  string orderId = 1;
  string driverId = 2; 
  int32 minutes = 3;
}

message BidResponse {
  bool success = 1;
  string message = 2;
}

message GetAvailableOrdersRequest {
}
