// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: pricing/proto/pricing.proto

package proto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CalculatePriceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerLat   float64                `protobuf:"fixed64,1,opt,name=customerLat,proto3" json:"customerLat,omitempty"`
	CustomerLon   float64                `protobuf:"fixed64,2,opt,name=customerLon,proto3" json:"customerLon,omitempty"`
	RestaurantLat float64                `protobuf:"fixed64,3,opt,name=restaurantLat,proto3" json:"restaurantLat,omitempty"`
	RestaurantLon float64                `protobuf:"fixed64,4,opt,name=restaurantLon,proto3" json:"restaurantLon,omitempty"`
	IsPriority    bool                   `protobuf:"varint,5,opt,name=isPriority,proto3" json:"isPriority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculatePriceRequest) Reset() {
	*x = CalculatePriceRequest{}
	mi := &file_pricing_proto_pricing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculatePriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculatePriceRequest) ProtoMessage() {}

func (x *CalculatePriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pricing_proto_pricing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculatePriceRequest.ProtoReflect.Descriptor instead.
func (*CalculatePriceRequest) Descriptor() ([]byte, []int) {
	return file_pricing_proto_pricing_proto_rawDescGZIP(), []int{0}
}

func (x *CalculatePriceRequest) GetCustomerLat() float64 {
	if x != nil {
		return x.CustomerLat
	}
	return 0
}

func (x *CalculatePriceRequest) GetCustomerLon() float64 {
	if x != nil {
		return x.CustomerLon
	}
	return 0
}

func (x *CalculatePriceRequest) GetRestaurantLat() float64 {
	if x != nil {
		return x.RestaurantLat
	}
	return 0
}

func (x *CalculatePriceRequest) GetRestaurantLon() float64 {
	if x != nil {
		return x.RestaurantLon
	}
	return 0
}

func (x *CalculatePriceRequest) GetIsPriority() bool {
	if x != nil {
		return x.IsPriority
	}
	return false
}

type CalculatePriceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FinalPrice    float64                `protobuf:"fixed64,1,opt,name=finalPrice,proto3" json:"finalPrice,omitempty"`
	DistanceKm    float64                `protobuf:"fixed64,2,opt,name=distanceKm,proto3" json:"distanceKm,omitempty"`
	BasePrice     float64                `protobuf:"fixed64,3,opt,name=basePrice,proto3" json:"basePrice,omitempty"`
	DistancePrice float64                `protobuf:"fixed64,4,opt,name=distancePrice,proto3" json:"distancePrice,omitempty"`
	RushHourFee   float64                `protobuf:"fixed64,5,opt,name=rushHourFee,proto3" json:"rushHourFee,omitempty"`
	WeatherFee    float64                `protobuf:"fixed64,6,opt,name=weatherFee,proto3" json:"weatherFee,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculatePriceResponse) Reset() {
	*x = CalculatePriceResponse{}
	mi := &file_pricing_proto_pricing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculatePriceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculatePriceResponse) ProtoMessage() {}

func (x *CalculatePriceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pricing_proto_pricing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculatePriceResponse.ProtoReflect.Descriptor instead.
func (*CalculatePriceResponse) Descriptor() ([]byte, []int) {
	return file_pricing_proto_pricing_proto_rawDescGZIP(), []int{1}
}

func (x *CalculatePriceResponse) GetFinalPrice() float64 {
	if x != nil {
		return x.FinalPrice
	}
	return 0
}

func (x *CalculatePriceResponse) GetDistanceKm() float64 {
	if x != nil {
		return x.DistanceKm
	}
	return 0
}

func (x *CalculatePriceResponse) GetBasePrice() float64 {
	if x != nil {
		return x.BasePrice
	}
	return 0
}

func (x *CalculatePriceResponse) GetDistancePrice() float64 {
	if x != nil {
		return x.DistancePrice
	}
	return 0
}

func (x *CalculatePriceResponse) GetRushHourFee() float64 {
	if x != nil {
		return x.RushHourFee
	}
	return 0
}

func (x *CalculatePriceResponse) GetWeatherFee() float64 {
	if x != nil {
		return x.WeatherFee
	}
	return 0
}

type UpdateRulesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BasePrice     float64                `protobuf:"fixed64,1,opt,name=basePrice,proto3" json:"basePrice,omitempty"`
	PricePerKm    float64                `protobuf:"fixed64,2,opt,name=pricePerKm,proto3" json:"pricePerKm,omitempty"`
	RushHourFee   float64                `protobuf:"fixed64,3,opt,name=rushHourFee,proto3" json:"rushHourFee,omitempty"`
	WeatherFee    float64                `protobuf:"fixed64,4,opt,name=weatherFee,proto3" json:"weatherFee,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRulesRequest) Reset() {
	*x = UpdateRulesRequest{}
	mi := &file_pricing_proto_pricing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRulesRequest) ProtoMessage() {}

func (x *UpdateRulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pricing_proto_pricing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRulesRequest.ProtoReflect.Descriptor instead.
func (*UpdateRulesRequest) Descriptor() ([]byte, []int) {
	return file_pricing_proto_pricing_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateRulesRequest) GetBasePrice() float64 {
	if x != nil {
		return x.BasePrice
	}
	return 0
}

func (x *UpdateRulesRequest) GetPricePerKm() float64 {
	if x != nil {
		return x.PricePerKm
	}
	return 0
}

func (x *UpdateRulesRequest) GetRushHourFee() float64 {
	if x != nil {
		return x.RushHourFee
	}
	return 0
}

func (x *UpdateRulesRequest) GetWeatherFee() float64 {
	if x != nil {
		return x.WeatherFee
	}
	return 0
}

type PricingRulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BasePrice     float64                `protobuf:"fixed64,2,opt,name=basePrice,proto3" json:"basePrice,omitempty"`
	PricePerKm    float64                `protobuf:"fixed64,3,opt,name=pricePerKm,proto3" json:"pricePerKm,omitempty"`
	RushHourFee   float64                `protobuf:"fixed64,4,opt,name=rushHourFee,proto3" json:"rushHourFee,omitempty"`
	WeatherFee    float64                `protobuf:"fixed64,5,opt,name=weatherFee,proto3" json:"weatherFee,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PricingRulesResponse) Reset() {
	*x = PricingRulesResponse{}
	mi := &file_pricing_proto_pricing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PricingRulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PricingRulesResponse) ProtoMessage() {}

func (x *PricingRulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pricing_proto_pricing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PricingRulesResponse.ProtoReflect.Descriptor instead.
func (*PricingRulesResponse) Descriptor() ([]byte, []int) {
	return file_pricing_proto_pricing_proto_rawDescGZIP(), []int{3}
}

func (x *PricingRulesResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PricingRulesResponse) GetBasePrice() float64 {
	if x != nil {
		return x.BasePrice
	}
	return 0
}

func (x *PricingRulesResponse) GetPricePerKm() float64 {
	if x != nil {
		return x.PricePerKm
	}
	return 0
}

func (x *PricingRulesResponse) GetRushHourFee() float64 {
	if x != nil {
		return x.RushHourFee
	}
	return 0
}

func (x *PricingRulesResponse) GetWeatherFee() float64 {
	if x != nil {
		return x.WeatherFee
	}
	return 0
}

type UpdateStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsRushHour    bool                   `protobuf:"varint,1,opt,name=isRushHour,proto3" json:"isRushHour,omitempty"`
	IsBadWeather  bool                   `protobuf:"varint,2,opt,name=isBadWeather,proto3" json:"isBadWeather,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStatusRequest) Reset() {
	*x = UpdateStatusRequest{}
	mi := &file_pricing_proto_pricing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusRequest) ProtoMessage() {}

func (x *UpdateStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pricing_proto_pricing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateStatusRequest) Descriptor() ([]byte, []int) {
	return file_pricing_proto_pricing_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateStatusRequest) GetIsRushHour() bool {
	if x != nil {
		return x.IsRushHour
	}
	return false
}

func (x *UpdateStatusRequest) GetIsBadWeather() bool {
	if x != nil {
		return x.IsBadWeather
	}
	return false
}

type SystemStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsRushHour    bool                   `protobuf:"varint,1,opt,name=isRushHour,proto3" json:"isRushHour,omitempty"`
	IsBadWeather  bool                   `protobuf:"varint,2,opt,name=isBadWeather,proto3" json:"isBadWeather,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemStatusResponse) Reset() {
	*x = SystemStatusResponse{}
	mi := &file_pricing_proto_pricing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemStatusResponse) ProtoMessage() {}

func (x *SystemStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pricing_proto_pricing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemStatusResponse.ProtoReflect.Descriptor instead.
func (*SystemStatusResponse) Descriptor() ([]byte, []int) {
	return file_pricing_proto_pricing_proto_rawDescGZIP(), []int{5}
}

func (x *SystemStatusResponse) GetIsRushHour() bool {
	if x != nil {
		return x.IsRushHour
	}
	return false
}

func (x *SystemStatusResponse) GetIsBadWeather() bool {
	if x != nil {
		return x.IsBadWeather
	}
	return false
}

type GetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigRequest) Reset() {
	*x = GetConfigRequest{}
	mi := &file_pricing_proto_pricing_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRequest) ProtoMessage() {}

func (x *GetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pricing_proto_pricing_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRequest.ProtoReflect.Descriptor instead.
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return file_pricing_proto_pricing_proto_rawDescGZIP(), []int{6}
}

type ConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rules         *PricingRulesResponse  `protobuf:"bytes,1,opt,name=rules,proto3" json:"rules,omitempty"`
	Status        *SystemStatusResponse  `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigResponse) Reset() {
	*x = ConfigResponse{}
	mi := &file_pricing_proto_pricing_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigResponse) ProtoMessage() {}

func (x *ConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pricing_proto_pricing_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigResponse.ProtoReflect.Descriptor instead.
func (*ConfigResponse) Descriptor() ([]byte, []int) {
	return file_pricing_proto_pricing_proto_rawDescGZIP(), []int{7}
}

func (x *ConfigResponse) GetRules() *PricingRulesResponse {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *ConfigResponse) GetStatus() *SystemStatusResponse {
	if x != nil {
		return x.Status
	}
	return nil
}

var File_pricing_proto_pricing_proto protoreflect.FileDescriptor

const file_pricing_proto_pricing_proto_rawDesc = "" +
	"\n" +
	"\x1bpricing/proto/pricing.proto\x12\apricing\x1a\x1cgoogle/api/annotations.proto\"\xc7\x01\n" +
	"\x15CalculatePriceRequest\x12 \n" +
	"\vcustomerLat\x18\x01 \x01(\x01R\vcustomerLat\x12 \n" +
	"\vcustomerLon\x18\x02 \x01(\x01R\vcustomerLon\x12$\n" +
	"\rrestaurantLat\x18\x03 \x01(\x01R\rrestaurantLat\x12$\n" +
	"\rrestaurantLon\x18\x04 \x01(\x01R\rrestaurantLon\x12\x1e\n" +
	"\n" +
	"isPriority\x18\x05 \x01(\bR\n" +
	"isPriority\"\xde\x01\n" +
	"\x16CalculatePriceResponse\x12\x1e\n" +
	"\n" +
	"finalPrice\x18\x01 \x01(\x01R\n" +
	"finalPrice\x12\x1e\n" +
	"\n" +
	"distanceKm\x18\x02 \x01(\x01R\n" +
	"distanceKm\x12\x1c\n" +
	"\tbasePrice\x18\x03 \x01(\x01R\tbasePrice\x12$\n" +
	"\rdistancePrice\x18\x04 \x01(\x01R\rdistancePrice\x12 \n" +
	"\vrushHourFee\x18\x05 \x01(\x01R\vrushHourFee\x12\x1e\n" +
	"\n" +
	"weatherFee\x18\x06 \x01(\x01R\n" +
	"weatherFee\"\x94\x01\n" +
	"\x12UpdateRulesRequest\x12\x1c\n" +
	"\tbasePrice\x18\x01 \x01(\x01R\tbasePrice\x12\x1e\n" +
	"\n" +
	"pricePerKm\x18\x02 \x01(\x01R\n" +
	"pricePerKm\x12 \n" +
	"\vrushHourFee\x18\x03 \x01(\x01R\vrushHourFee\x12\x1e\n" +
	"\n" +
	"weatherFee\x18\x04 \x01(\x01R\n" +
	"weatherFee\"\xa6\x01\n" +
	"\x14PricingRulesResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\tbasePrice\x18\x02 \x01(\x01R\tbasePrice\x12\x1e\n" +
	"\n" +
	"pricePerKm\x18\x03 \x01(\x01R\n" +
	"pricePerKm\x12 \n" +
	"\vrushHourFee\x18\x04 \x01(\x01R\vrushHourFee\x12\x1e\n" +
	"\n" +
	"weatherFee\x18\x05 \x01(\x01R\n" +
	"weatherFee\"Y\n" +
	"\x13UpdateStatusRequest\x12\x1e\n" +
	"\n" +
	"isRushHour\x18\x01 \x01(\bR\n" +
	"isRushHour\x12\"\n" +
	"\fisBadWeather\x18\x02 \x01(\bR\fisBadWeather\"Z\n" +
	"\x14SystemStatusResponse\x12\x1e\n" +
	"\n" +
	"isRushHour\x18\x01 \x01(\bR\n" +
	"isRushHour\x12\"\n" +
	"\fisBadWeather\x18\x02 \x01(\bR\fisBadWeather\"\x12\n" +
	"\x10GetConfigRequest\"|\n" +
	"\x0eConfigResponse\x123\n" +
	"\x05rules\x18\x01 \x01(\v2\x1d.pricing.PricingRulesResponseR\x05rules\x125\n" +
	"\x06status\x18\x02 \x01(\v2\x1d.pricing.SystemStatusResponseR\x06status2\xbf\x03\n" +
	"\x0ePricingService\x12p\n" +
	"\x0eCalculatePrice\x12\x1e.pricing.CalculatePriceRequest\x1a\x1f.pricing.CalculatePriceResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/pricing/calculate\x12k\n" +
	"\x12UpdatePricingRules\x12\x1b.pricing.UpdateRulesRequest\x1a\x1d.pricing.PricingRulesResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/pricing/rules\x12m\n" +
	"\x12UpdateSystemStatus\x12\x1c.pricing.UpdateStatusRequest\x1a\x1d.pricing.SystemStatusResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\x1a\x0f/pricing/status\x12_\n" +
	"\x10GetCurrentConfig\x12\x19.pricing.GetConfigRequest\x1a\x17.pricing.ConfigResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/pricing/configB\x16Z\x14common/pricing/protob\x06proto3"

var (
	file_pricing_proto_pricing_proto_rawDescOnce sync.Once
	file_pricing_proto_pricing_proto_rawDescData []byte
)

func file_pricing_proto_pricing_proto_rawDescGZIP() []byte {
	file_pricing_proto_pricing_proto_rawDescOnce.Do(func() {
		file_pricing_proto_pricing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pricing_proto_pricing_proto_rawDesc), len(file_pricing_proto_pricing_proto_rawDesc)))
	})
	return file_pricing_proto_pricing_proto_rawDescData
}

var file_pricing_proto_pricing_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pricing_proto_pricing_proto_goTypes = []any{
	(*CalculatePriceRequest)(nil),  // 0: pricing.CalculatePriceRequest
	(*CalculatePriceResponse)(nil), // 1: pricing.CalculatePriceResponse
	(*UpdateRulesRequest)(nil),     // 2: pricing.UpdateRulesRequest
	(*PricingRulesResponse)(nil),   // 3: pricing.PricingRulesResponse
	(*UpdateStatusRequest)(nil),    // 4: pricing.UpdateStatusRequest
	(*SystemStatusResponse)(nil),   // 5: pricing.SystemStatusResponse
	(*GetConfigRequest)(nil),       // 6: pricing.GetConfigRequest
	(*ConfigResponse)(nil),         // 7: pricing.ConfigResponse
}
var file_pricing_proto_pricing_proto_depIdxs = []int32{
	3, // 0: pricing.ConfigResponse.rules:type_name -> pricing.PricingRulesResponse
	5, // 1: pricing.ConfigResponse.status:type_name -> pricing.SystemStatusResponse
	0, // 2: pricing.PricingService.CalculatePrice:input_type -> pricing.CalculatePriceRequest
	2, // 3: pricing.PricingService.UpdatePricingRules:input_type -> pricing.UpdateRulesRequest
	4, // 4: pricing.PricingService.UpdateSystemStatus:input_type -> pricing.UpdateStatusRequest
	6, // 5: pricing.PricingService.GetCurrentConfig:input_type -> pricing.GetConfigRequest
	1, // 6: pricing.PricingService.CalculatePrice:output_type -> pricing.CalculatePriceResponse
	3, // 7: pricing.PricingService.UpdatePricingRules:output_type -> pricing.PricingRulesResponse
	5, // 8: pricing.PricingService.UpdateSystemStatus:output_type -> pricing.SystemStatusResponse
	7, // 9: pricing.PricingService.GetCurrentConfig:output_type -> pricing.ConfigResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pricing_proto_pricing_proto_init() }
func file_pricing_proto_pricing_proto_init() {
	if File_pricing_proto_pricing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pricing_proto_pricing_proto_rawDesc), len(file_pricing_proto_pricing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pricing_proto_pricing_proto_goTypes,
		DependencyIndexes: file_pricing_proto_pricing_proto_depIdxs,
		MessageInfos:      file_pricing_proto_pricing_proto_msgTypes,
	}.Build()
	File_pricing_proto_pricing_proto = out.File
	file_pricing_proto_pricing_proto_goTypes = nil
	file_pricing_proto_pricing_proto_depIdxs = nil
}
