// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: analysis/proto/analysis.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AnalysisService_CalculateFees_FullMethodName          = "/analysis.AnalysisService/CalculateFees"
	AnalysisService_UpdateFeeConfiguration_FullMethodName = "/analysis.AnalysisService/UpdateFeeConfiguration"
	AnalysisService_GetCurrentConfig_FullMethodName       = "/analysis.AnalysisService/GetCurrentConfig"
	AnalysisService_RecordOrderProfit_FullMethodName      = "/analysis.AnalysisService/RecordOrderProfit"
	AnalysisService_GetAnalytics_FullMethodName           = "/analysis.AnalysisService/GetAnalytics"
	AnalysisService_GetProfitHistory_FullMethodName       = "/analysis.AnalysisService/GetProfitHistory"
)

// AnalysisServiceClient is the client API for AnalysisService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AnalysisServiceClient interface {
	CalculateFees(ctx context.Context, in *CalculationRequest, opts ...grpc.CallOption) (*FeeResponse, error)
	UpdateFeeConfiguration(ctx context.Context, in *UpdateConfigRequest, opts ...grpc.CallOption) (*FeeConfigResponse, error)
	GetCurrentConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*FeeConfigResponse, error)
	RecordOrderProfit(ctx context.Context, in *RecordProfitRequest, opts ...grpc.CallOption) (*RecordProfitResponse, error)
	GetAnalytics(ctx context.Context, in *GetAnalyticsRequest, opts ...grpc.CallOption) (*AnalyticsResponse, error)
	GetProfitHistory(ctx context.Context, in *GetHistoryRequest, opts ...grpc.CallOption) (*HistoryResponse, error)
}

type analysisServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnalysisServiceClient(cc grpc.ClientConnInterface) AnalysisServiceClient {
	return &analysisServiceClient{cc}
}

func (c *analysisServiceClient) CalculateFees(ctx context.Context, in *CalculationRequest, opts ...grpc.CallOption) (*FeeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FeeResponse)
	err := c.cc.Invoke(ctx, AnalysisService_CalculateFees_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analysisServiceClient) UpdateFeeConfiguration(ctx context.Context, in *UpdateConfigRequest, opts ...grpc.CallOption) (*FeeConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FeeConfigResponse)
	err := c.cc.Invoke(ctx, AnalysisService_UpdateFeeConfiguration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analysisServiceClient) GetCurrentConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*FeeConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FeeConfigResponse)
	err := c.cc.Invoke(ctx, AnalysisService_GetCurrentConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analysisServiceClient) RecordOrderProfit(ctx context.Context, in *RecordProfitRequest, opts ...grpc.CallOption) (*RecordProfitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordProfitResponse)
	err := c.cc.Invoke(ctx, AnalysisService_RecordOrderProfit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analysisServiceClient) GetAnalytics(ctx context.Context, in *GetAnalyticsRequest, opts ...grpc.CallOption) (*AnalyticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyticsResponse)
	err := c.cc.Invoke(ctx, AnalysisService_GetAnalytics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analysisServiceClient) GetProfitHistory(ctx context.Context, in *GetHistoryRequest, opts ...grpc.CallOption) (*HistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HistoryResponse)
	err := c.cc.Invoke(ctx, AnalysisService_GetProfitHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnalysisServiceServer is the server API for AnalysisService service.
// All implementations must embed UnimplementedAnalysisServiceServer
// for forward compatibility.
type AnalysisServiceServer interface {
	CalculateFees(context.Context, *CalculationRequest) (*FeeResponse, error)
	UpdateFeeConfiguration(context.Context, *UpdateConfigRequest) (*FeeConfigResponse, error)
	GetCurrentConfig(context.Context, *GetConfigRequest) (*FeeConfigResponse, error)
	RecordOrderProfit(context.Context, *RecordProfitRequest) (*RecordProfitResponse, error)
	GetAnalytics(context.Context, *GetAnalyticsRequest) (*AnalyticsResponse, error)
	GetProfitHistory(context.Context, *GetHistoryRequest) (*HistoryResponse, error)
	mustEmbedUnimplementedAnalysisServiceServer()
}

// UnimplementedAnalysisServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnalysisServiceServer struct{}

func (UnimplementedAnalysisServiceServer) CalculateFees(context.Context, *CalculationRequest) (*FeeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalculateFees not implemented")
}
func (UnimplementedAnalysisServiceServer) UpdateFeeConfiguration(context.Context, *UpdateConfigRequest) (*FeeConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFeeConfiguration not implemented")
}
func (UnimplementedAnalysisServiceServer) GetCurrentConfig(context.Context, *GetConfigRequest) (*FeeConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCurrentConfig not implemented")
}
func (UnimplementedAnalysisServiceServer) RecordOrderProfit(context.Context, *RecordProfitRequest) (*RecordProfitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecordOrderProfit not implemented")
}
func (UnimplementedAnalysisServiceServer) GetAnalytics(context.Context, *GetAnalyticsRequest) (*AnalyticsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAnalytics not implemented")
}
func (UnimplementedAnalysisServiceServer) GetProfitHistory(context.Context, *GetHistoryRequest) (*HistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProfitHistory not implemented")
}
func (UnimplementedAnalysisServiceServer) mustEmbedUnimplementedAnalysisServiceServer() {}
func (UnimplementedAnalysisServiceServer) testEmbeddedByValue()                         {}

// UnsafeAnalysisServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnalysisServiceServer will
// result in compilation errors.
type UnsafeAnalysisServiceServer interface {
	mustEmbedUnimplementedAnalysisServiceServer()
}

func RegisterAnalysisServiceServer(s grpc.ServiceRegistrar, srv AnalysisServiceServer) {
	// If the following call pancis, it indicates UnimplementedAnalysisServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AnalysisService_ServiceDesc, srv)
}

func _AnalysisService_CalculateFees_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalysisServiceServer).CalculateFees(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalysisService_CalculateFees_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalysisServiceServer).CalculateFees(ctx, req.(*CalculationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalysisService_UpdateFeeConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalysisServiceServer).UpdateFeeConfiguration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalysisService_UpdateFeeConfiguration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalysisServiceServer).UpdateFeeConfiguration(ctx, req.(*UpdateConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalysisService_GetCurrentConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalysisServiceServer).GetCurrentConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalysisService_GetCurrentConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalysisServiceServer).GetCurrentConfig(ctx, req.(*GetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalysisService_RecordOrderProfit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordProfitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalysisServiceServer).RecordOrderProfit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalysisService_RecordOrderProfit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalysisServiceServer).RecordOrderProfit(ctx, req.(*RecordProfitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalysisService_GetAnalytics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAnalyticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalysisServiceServer).GetAnalytics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalysisService_GetAnalytics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalysisServiceServer).GetAnalytics(ctx, req.(*GetAnalyticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalysisService_GetProfitHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalysisServiceServer).GetProfitHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalysisService_GetProfitHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalysisServiceServer).GetProfitHistory(ctx, req.(*GetHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AnalysisService_ServiceDesc is the grpc.ServiceDesc for AnalysisService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnalysisService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "analysis.AnalysisService",
	HandlerType: (*AnalysisServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CalculateFees",
			Handler:    _AnalysisService_CalculateFees_Handler,
		},
		{
			MethodName: "UpdateFeeConfiguration",
			Handler:    _AnalysisService_UpdateFeeConfiguration_Handler,
		},
		{
			MethodName: "GetCurrentConfig",
			Handler:    _AnalysisService_GetCurrentConfig_Handler,
		},
		{
			MethodName: "RecordOrderProfit",
			Handler:    _AnalysisService_RecordOrderProfit_Handler,
		},
		{
			MethodName: "GetAnalytics",
			Handler:    _AnalysisService_GetAnalytics_Handler,
		},
		{
			MethodName: "GetProfitHistory",
			Handler:    _AnalysisService_GetProfitHistory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "analysis/proto/analysis.proto",
}
