// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: analysis/proto/analysis.proto

package proto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CalculationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemsTotal    float64                `protobuf:"fixed64,1,opt,name=itemsTotal,proto3" json:"itemsTotal,omitempty"`       // Price of food
	DeliveryPrice float64                `protobuf:"fixed64,2,opt,name=deliveryPrice,proto3" json:"deliveryPrice,omitempty"` // Price from Pricing Service
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculationRequest) Reset() {
	*x = CalculationRequest{}
	mi := &file_analysis_proto_analysis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculationRequest) ProtoMessage() {}

func (x *CalculationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_proto_analysis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculationRequest.ProtoReflect.Descriptor instead.
func (*CalculationRequest) Descriptor() ([]byte, []int) {
	return file_analysis_proto_analysis_proto_rawDescGZIP(), []int{0}
}

func (x *CalculationRequest) GetItemsTotal() float64 {
	if x != nil {
		return x.ItemsTotal
	}
	return 0
}

func (x *CalculationRequest) GetDeliveryPrice() float64 {
	if x != nil {
		return x.DeliveryPrice
	}
	return 0
}

type FeeResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AppFee             float64                `protobuf:"fixed64,1,opt,name=appFee,proto3" json:"appFee,omitempty"`
	SmallOrderFee      float64                `protobuf:"fixed64,2,opt,name=smallOrderFee,proto3" json:"smallOrderFee,omitempty"`
	EstimatedProfit    float64                `protobuf:"fixed64,3,opt,name=estimatedProfit,proto3" json:"estimatedProfit,omitempty"`
	ProfitFromItems    float64                `protobuf:"fixed64,4,opt,name=profitFromItems,proto3" json:"profitFromItems,omitempty"`       // NEW
	ProfitFromDelivery float64                `protobuf:"fixed64,5,opt,name=profitFromDelivery,proto3" json:"profitFromDelivery,omitempty"` // NEW
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *FeeResponse) Reset() {
	*x = FeeResponse{}
	mi := &file_analysis_proto_analysis_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeeResponse) ProtoMessage() {}

func (x *FeeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_proto_analysis_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeeResponse.ProtoReflect.Descriptor instead.
func (*FeeResponse) Descriptor() ([]byte, []int) {
	return file_analysis_proto_analysis_proto_rawDescGZIP(), []int{1}
}

func (x *FeeResponse) GetAppFee() float64 {
	if x != nil {
		return x.AppFee
	}
	return 0
}

func (x *FeeResponse) GetSmallOrderFee() float64 {
	if x != nil {
		return x.SmallOrderFee
	}
	return 0
}

func (x *FeeResponse) GetEstimatedProfit() float64 {
	if x != nil {
		return x.EstimatedProfit
	}
	return 0
}

func (x *FeeResponse) GetProfitFromItems() float64 {
	if x != nil {
		return x.ProfitFromItems
	}
	return 0
}

func (x *FeeResponse) GetProfitFromDelivery() float64 {
	if x != nil {
		return x.ProfitFromDelivery
	}
	return 0
}

type UpdateConfigRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	ItemRevenuePercent     float64                `protobuf:"fixed64,1,opt,name=itemRevenuePercent,proto3" json:"itemRevenuePercent,omitempty"`         // e.g. 10% from restaurant
	DeliveryRevenuePercent float64                `protobuf:"fixed64,2,opt,name=deliveryRevenuePercent,proto3" json:"deliveryRevenuePercent,omitempty"` // e.g. 5% from delivery fee
	AppFeePercent          float64                `protobuf:"fixed64,3,opt,name=appFeePercent,proto3" json:"appFeePercent,omitempty"`                   // e.g. 6%
	AppFeeCap              float64                `protobuf:"fixed64,4,opt,name=appFeeCap,proto3" json:"appFeeCap,omitempty"`                           // e.g. 250 RSD
	SmallOrderThreshold    float64                `protobuf:"fixed64,5,opt,name=smallOrderThreshold,proto3" json:"smallOrderThreshold,omitempty"`       // e.g. 599 RSD
	SmallOrderFee          float64                `protobuf:"fixed64,6,opt,name=smallOrderFee,proto3" json:"smallOrderFee,omitempty"`                   // e.g. 149 RSD
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *UpdateConfigRequest) Reset() {
	*x = UpdateConfigRequest{}
	mi := &file_analysis_proto_analysis_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigRequest) ProtoMessage() {}

func (x *UpdateConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_proto_analysis_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateConfigRequest) Descriptor() ([]byte, []int) {
	return file_analysis_proto_analysis_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateConfigRequest) GetItemRevenuePercent() float64 {
	if x != nil {
		return x.ItemRevenuePercent
	}
	return 0
}

func (x *UpdateConfigRequest) GetDeliveryRevenuePercent() float64 {
	if x != nil {
		return x.DeliveryRevenuePercent
	}
	return 0
}

func (x *UpdateConfigRequest) GetAppFeePercent() float64 {
	if x != nil {
		return x.AppFeePercent
	}
	return 0
}

func (x *UpdateConfigRequest) GetAppFeeCap() float64 {
	if x != nil {
		return x.AppFeeCap
	}
	return 0
}

func (x *UpdateConfigRequest) GetSmallOrderThreshold() float64 {
	if x != nil {
		return x.SmallOrderThreshold
	}
	return 0
}

func (x *UpdateConfigRequest) GetSmallOrderFee() float64 {
	if x != nil {
		return x.SmallOrderFee
	}
	return 0
}

type FeeConfigResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Id                     string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ItemRevenuePercent     float64                `protobuf:"fixed64,2,opt,name=itemRevenuePercent,proto3" json:"itemRevenuePercent,omitempty"`
	DeliveryRevenuePercent float64                `protobuf:"fixed64,3,opt,name=deliveryRevenuePercent,proto3" json:"deliveryRevenuePercent,omitempty"`
	AppFeePercent          float64                `protobuf:"fixed64,4,opt,name=appFeePercent,proto3" json:"appFeePercent,omitempty"`
	AppFeeCap              float64                `protobuf:"fixed64,5,opt,name=appFeeCap,proto3" json:"appFeeCap,omitempty"`
	SmallOrderThreshold    float64                `protobuf:"fixed64,6,opt,name=smallOrderThreshold,proto3" json:"smallOrderThreshold,omitempty"`
	SmallOrderFee          float64                `protobuf:"fixed64,7,opt,name=smallOrderFee,proto3" json:"smallOrderFee,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *FeeConfigResponse) Reset() {
	*x = FeeConfigResponse{}
	mi := &file_analysis_proto_analysis_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeeConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeeConfigResponse) ProtoMessage() {}

func (x *FeeConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_proto_analysis_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeeConfigResponse.ProtoReflect.Descriptor instead.
func (*FeeConfigResponse) Descriptor() ([]byte, []int) {
	return file_analysis_proto_analysis_proto_rawDescGZIP(), []int{3}
}

func (x *FeeConfigResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FeeConfigResponse) GetItemRevenuePercent() float64 {
	if x != nil {
		return x.ItemRevenuePercent
	}
	return 0
}

func (x *FeeConfigResponse) GetDeliveryRevenuePercent() float64 {
	if x != nil {
		return x.DeliveryRevenuePercent
	}
	return 0
}

func (x *FeeConfigResponse) GetAppFeePercent() float64 {
	if x != nil {
		return x.AppFeePercent
	}
	return 0
}

func (x *FeeConfigResponse) GetAppFeeCap() float64 {
	if x != nil {
		return x.AppFeeCap
	}
	return 0
}

func (x *FeeConfigResponse) GetSmallOrderThreshold() float64 {
	if x != nil {
		return x.SmallOrderThreshold
	}
	return 0
}

func (x *FeeConfigResponse) GetSmallOrderFee() float64 {
	if x != nil {
		return x.SmallOrderFee
	}
	return 0
}

type GetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigRequest) Reset() {
	*x = GetConfigRequest{}
	mi := &file_analysis_proto_analysis_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRequest) ProtoMessage() {}

func (x *GetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_proto_analysis_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRequest.ProtoReflect.Descriptor instead.
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return file_analysis_proto_analysis_proto_rawDescGZIP(), []int{4}
}

type RecordProfitRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	OrderId            string                 `protobuf:"bytes,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	RestaurantId       string                 `protobuf:"bytes,2,opt,name=restaurantId,proto3" json:"restaurantId,omitempty"`
	UserId             string                 `protobuf:"bytes,3,opt,name=userId,proto3" json:"userId,omitempty"`
	AppFee             float64                `protobuf:"fixed64,4,opt,name=appFee,proto3" json:"appFee,omitempty"`
	SmallOrderFee      float64                `protobuf:"fixed64,5,opt,name=smallOrderFee,proto3" json:"smallOrderFee,omitempty"`
	ProfitFromItems    float64                `protobuf:"fixed64,6,opt,name=profitFromItems,proto3" json:"profitFromItems,omitempty"`
	ProfitFromDelivery float64                `protobuf:"fixed64,7,opt,name=profitFromDelivery,proto3" json:"profitFromDelivery,omitempty"`
	TotalProfit        float64                `protobuf:"fixed64,8,opt,name=totalProfit,proto3" json:"totalProfit,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RecordProfitRequest) Reset() {
	*x = RecordProfitRequest{}
	mi := &file_analysis_proto_analysis_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordProfitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordProfitRequest) ProtoMessage() {}

func (x *RecordProfitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_proto_analysis_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordProfitRequest.ProtoReflect.Descriptor instead.
func (*RecordProfitRequest) Descriptor() ([]byte, []int) {
	return file_analysis_proto_analysis_proto_rawDescGZIP(), []int{5}
}

func (x *RecordProfitRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *RecordProfitRequest) GetRestaurantId() string {
	if x != nil {
		return x.RestaurantId
	}
	return ""
}

func (x *RecordProfitRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RecordProfitRequest) GetAppFee() float64 {
	if x != nil {
		return x.AppFee
	}
	return 0
}

func (x *RecordProfitRequest) GetSmallOrderFee() float64 {
	if x != nil {
		return x.SmallOrderFee
	}
	return 0
}

func (x *RecordProfitRequest) GetProfitFromItems() float64 {
	if x != nil {
		return x.ProfitFromItems
	}
	return 0
}

func (x *RecordProfitRequest) GetProfitFromDelivery() float64 {
	if x != nil {
		return x.ProfitFromDelivery
	}
	return 0
}

func (x *RecordProfitRequest) GetTotalProfit() float64 {
	if x != nil {
		return x.TotalProfit
	}
	return 0
}

type RecordProfitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordProfitResponse) Reset() {
	*x = RecordProfitResponse{}
	mi := &file_analysis_proto_analysis_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordProfitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordProfitResponse) ProtoMessage() {}

func (x *RecordProfitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_proto_analysis_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordProfitResponse.ProtoReflect.Descriptor instead.
func (*RecordProfitResponse) Descriptor() ([]byte, []int) {
	return file_analysis_proto_analysis_proto_rawDescGZIP(), []int{6}
}

func (x *RecordProfitResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type TopEntity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopEntity) Reset() {
	*x = TopEntity{}
	mi := &file_analysis_proto_analysis_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopEntity) ProtoMessage() {}

func (x *TopEntity) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_proto_analysis_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopEntity.ProtoReflect.Descriptor instead.
func (*TopEntity) Descriptor() ([]byte, []int) {
	return file_analysis_proto_analysis_proto_rawDescGZIP(), []int{7}
}

func (x *TopEntity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TopEntity) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TopEntity) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type AnalyticsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TotalRevenue   float64                `protobuf:"fixed64,1,opt,name=totalRevenue,proto3" json:"totalRevenue,omitempty"`
	TopRestaurants []*TopEntity           `protobuf:"bytes,2,rep,name=topRestaurants,proto3" json:"topRestaurants,omitempty"`
	TopUsers       []*TopEntity           `protobuf:"bytes,3,rep,name=topUsers,proto3" json:"topUsers,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AnalyticsResponse) Reset() {
	*x = AnalyticsResponse{}
	mi := &file_analysis_proto_analysis_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyticsResponse) ProtoMessage() {}

func (x *AnalyticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_proto_analysis_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyticsResponse.ProtoReflect.Descriptor instead.
func (*AnalyticsResponse) Descriptor() ([]byte, []int) {
	return file_analysis_proto_analysis_proto_rawDescGZIP(), []int{8}
}

func (x *AnalyticsResponse) GetTotalRevenue() float64 {
	if x != nil {
		return x.TotalRevenue
	}
	return 0
}

func (x *AnalyticsResponse) GetTopRestaurants() []*TopEntity {
	if x != nil {
		return x.TopRestaurants
	}
	return nil
}

func (x *AnalyticsResponse) GetTopUsers() []*TopEntity {
	if x != nil {
		return x.TopUsers
	}
	return nil
}

type GetAnalyticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAnalyticsRequest) Reset() {
	*x = GetAnalyticsRequest{}
	mi := &file_analysis_proto_analysis_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnalyticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnalyticsRequest) ProtoMessage() {}

func (x *GetAnalyticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_proto_analysis_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnalyticsRequest.ProtoReflect.Descriptor instead.
func (*GetAnalyticsRequest) Descriptor() ([]byte, []int) {
	return file_analysis_proto_analysis_proto_rawDescGZIP(), []int{9}
}

type GetHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryRequest) Reset() {
	*x = GetHistoryRequest{}
	mi := &file_analysis_proto_analysis_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryRequest) ProtoMessage() {}

func (x *GetHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_proto_analysis_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetHistoryRequest) Descriptor() ([]byte, []int) {
	return file_analysis_proto_analysis_proto_rawDescGZIP(), []int{10}
}

type ProfitLogItem struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	OrderId            string                 `protobuf:"bytes,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	RestaurantId       string                 `protobuf:"bytes,2,opt,name=restaurantId,proto3" json:"restaurantId,omitempty"`
	AppFee             float64                `protobuf:"fixed64,3,opt,name=appFee,proto3" json:"appFee,omitempty"`
	SmallOrderFee      float64                `protobuf:"fixed64,4,opt,name=smallOrderFee,proto3" json:"smallOrderFee,omitempty"`
	ProfitFromItems    float64                `protobuf:"fixed64,5,opt,name=profitFromItems,proto3" json:"profitFromItems,omitempty"`
	ProfitFromDelivery float64                `protobuf:"fixed64,6,opt,name=profitFromDelivery,proto3" json:"profitFromDelivery,omitempty"`
	TotalProfit        float64                `protobuf:"fixed64,7,opt,name=totalProfit,proto3" json:"totalProfit,omitempty"`
	CreatedAt          string                 `protobuf:"bytes,8,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ProfitLogItem) Reset() {
	*x = ProfitLogItem{}
	mi := &file_analysis_proto_analysis_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfitLogItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfitLogItem) ProtoMessage() {}

func (x *ProfitLogItem) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_proto_analysis_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfitLogItem.ProtoReflect.Descriptor instead.
func (*ProfitLogItem) Descriptor() ([]byte, []int) {
	return file_analysis_proto_analysis_proto_rawDescGZIP(), []int{11}
}

func (x *ProfitLogItem) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ProfitLogItem) GetRestaurantId() string {
	if x != nil {
		return x.RestaurantId
	}
	return ""
}

func (x *ProfitLogItem) GetAppFee() float64 {
	if x != nil {
		return x.AppFee
	}
	return 0
}

func (x *ProfitLogItem) GetSmallOrderFee() float64 {
	if x != nil {
		return x.SmallOrderFee
	}
	return 0
}

func (x *ProfitLogItem) GetProfitFromItems() float64 {
	if x != nil {
		return x.ProfitFromItems
	}
	return 0
}

func (x *ProfitLogItem) GetProfitFromDelivery() float64 {
	if x != nil {
		return x.ProfitFromDelivery
	}
	return 0
}

func (x *ProfitLogItem) GetTotalProfit() float64 {
	if x != nil {
		return x.TotalProfit
	}
	return 0
}

func (x *ProfitLogItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type HistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*ProfitLogItem       `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryResponse) Reset() {
	*x = HistoryResponse{}
	mi := &file_analysis_proto_analysis_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryResponse) ProtoMessage() {}

func (x *HistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_proto_analysis_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryResponse.ProtoReflect.Descriptor instead.
func (*HistoryResponse) Descriptor() ([]byte, []int) {
	return file_analysis_proto_analysis_proto_rawDescGZIP(), []int{12}
}

func (x *HistoryResponse) GetLogs() []*ProfitLogItem {
	if x != nil {
		return x.Logs
	}
	return nil
}

var File_analysis_proto_analysis_proto protoreflect.FileDescriptor

const file_analysis_proto_analysis_proto_rawDesc = "" +
	"\n" +
	"\x1danalysis/proto/analysis.proto\x12\banalysis\x1a\x1cgoogle/api/annotations.proto\"Z\n" +
	"\x12CalculationRequest\x12\x1e\n" +
	"\n" +
	"itemsTotal\x18\x01 \x01(\x01R\n" +
	"itemsTotal\x12$\n" +
	"\rdeliveryPrice\x18\x02 \x01(\x01R\rdeliveryPrice\"\xcf\x01\n" +
	"\vFeeResponse\x12\x16\n" +
	"\x06appFee\x18\x01 \x01(\x01R\x06appFee\x12$\n" +
	"\rsmallOrderFee\x18\x02 \x01(\x01R\rsmallOrderFee\x12(\n" +
	"\x0festimatedProfit\x18\x03 \x01(\x01R\x0festimatedProfit\x12(\n" +
	"\x0fprofitFromItems\x18\x04 \x01(\x01R\x0fprofitFromItems\x12.\n" +
	"\x12profitFromDelivery\x18\x05 \x01(\x01R\x12profitFromDelivery\"\x99\x02\n" +
	"\x13UpdateConfigRequest\x12.\n" +
	"\x12itemRevenuePercent\x18\x01 \x01(\x01R\x12itemRevenuePercent\x126\n" +
	"\x16deliveryRevenuePercent\x18\x02 \x01(\x01R\x16deliveryRevenuePercent\x12$\n" +
	"\rappFeePercent\x18\x03 \x01(\x01R\rappFeePercent\x12\x1c\n" +
	"\tappFeeCap\x18\x04 \x01(\x01R\tappFeeCap\x120\n" +
	"\x13smallOrderThreshold\x18\x05 \x01(\x01R\x13smallOrderThreshold\x12$\n" +
	"\rsmallOrderFee\x18\x06 \x01(\x01R\rsmallOrderFee\"\xa7\x02\n" +
	"\x11FeeConfigResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12.\n" +
	"\x12itemRevenuePercent\x18\x02 \x01(\x01R\x12itemRevenuePercent\x126\n" +
	"\x16deliveryRevenuePercent\x18\x03 \x01(\x01R\x16deliveryRevenuePercent\x12$\n" +
	"\rappFeePercent\x18\x04 \x01(\x01R\rappFeePercent\x12\x1c\n" +
	"\tappFeeCap\x18\x05 \x01(\x01R\tappFeeCap\x120\n" +
	"\x13smallOrderThreshold\x18\x06 \x01(\x01R\x13smallOrderThreshold\x12$\n" +
	"\rsmallOrderFee\x18\a \x01(\x01R\rsmallOrderFee\"\x12\n" +
	"\x10GetConfigRequest\"\xa5\x02\n" +
	"\x13RecordProfitRequest\x12\x18\n" +
	"\aorderId\x18\x01 \x01(\tR\aorderId\x12\"\n" +
	"\frestaurantId\x18\x02 \x01(\tR\frestaurantId\x12\x16\n" +
	"\x06userId\x18\x03 \x01(\tR\x06userId\x12\x16\n" +
	"\x06appFee\x18\x04 \x01(\x01R\x06appFee\x12$\n" +
	"\rsmallOrderFee\x18\x05 \x01(\x01R\rsmallOrderFee\x12(\n" +
	"\x0fprofitFromItems\x18\x06 \x01(\x01R\x0fprofitFromItems\x12.\n" +
	"\x12profitFromDelivery\x18\a \x01(\x01R\x12profitFromDelivery\x12 \n" +
	"\vtotalProfit\x18\b \x01(\x01R\vtotalProfit\"0\n" +
	"\x14RecordProfitResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"I\n" +
	"\tTopEntity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\"\xa5\x01\n" +
	"\x11AnalyticsResponse\x12\"\n" +
	"\ftotalRevenue\x18\x01 \x01(\x01R\ftotalRevenue\x12;\n" +
	"\x0etopRestaurants\x18\x02 \x03(\v2\x13.analysis.TopEntityR\x0etopRestaurants\x12/\n" +
	"\btopUsers\x18\x03 \x03(\v2\x13.analysis.TopEntityR\btopUsers\"\x15\n" +
	"\x13GetAnalyticsRequest\"\x13\n" +
	"\x11GetHistoryRequest\"\xa5\x02\n" +
	"\rProfitLogItem\x12\x18\n" +
	"\aorderId\x18\x01 \x01(\tR\aorderId\x12\"\n" +
	"\frestaurantId\x18\x02 \x01(\tR\frestaurantId\x12\x16\n" +
	"\x06appFee\x18\x03 \x01(\x01R\x06appFee\x12$\n" +
	"\rsmallOrderFee\x18\x04 \x01(\x01R\rsmallOrderFee\x12(\n" +
	"\x0fprofitFromItems\x18\x05 \x01(\x01R\x0fprofitFromItems\x12.\n" +
	"\x12profitFromDelivery\x18\x06 \x01(\x01R\x12profitFromDelivery\x12 \n" +
	"\vtotalProfit\x18\a \x01(\x01R\vtotalProfit\x12\x1c\n" +
	"\tcreatedAt\x18\b \x01(\tR\tcreatedAt\">\n" +
	"\x0fHistoryResponse\x12+\n" +
	"\x04logs\x18\x01 \x03(\v2\x17.analysis.ProfitLogItemR\x04logs2\x92\x05\n" +
	"\x0fAnalysisService\x12d\n" +
	"\rCalculateFees\x12\x1c.analysis.CalculationRequest\x1a\x15.analysis.FeeResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/analysis/calculate\x12q\n" +
	"\x16UpdateFeeConfiguration\x12\x1d.analysis.UpdateConfigRequest\x1a\x1b.analysis.FeeConfigResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/analysis/config\x12e\n" +
	"\x10GetCurrentConfig\x12\x1a.analysis.GetConfigRequest\x1a\x1b.analysis.FeeConfigResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/analysis/config\x12o\n" +
	"\x11RecordOrderProfit\x12\x1d.analysis.RecordProfitRequest\x1a\x1e.analysis.RecordProfitResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/analysis/record\x12g\n" +
	"\fGetAnalytics\x12\x1d.analysis.GetAnalyticsRequest\x1a\x1b.analysis.AnalyticsResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/analysis/analytics\x12e\n" +
	"\x10GetProfitHistory\x12\x1b.analysis.GetHistoryRequest\x1a\x19.analysis.HistoryResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/analysis/historyB\x17Z\x15common/analysis/protob\x06proto3"

var (
	file_analysis_proto_analysis_proto_rawDescOnce sync.Once
	file_analysis_proto_analysis_proto_rawDescData []byte
)

func file_analysis_proto_analysis_proto_rawDescGZIP() []byte {
	file_analysis_proto_analysis_proto_rawDescOnce.Do(func() {
		file_analysis_proto_analysis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_analysis_proto_analysis_proto_rawDesc), len(file_analysis_proto_analysis_proto_rawDesc)))
	})
	return file_analysis_proto_analysis_proto_rawDescData
}

var file_analysis_proto_analysis_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_analysis_proto_analysis_proto_goTypes = []any{
	(*CalculationRequest)(nil),   // 0: analysis.CalculationRequest
	(*FeeResponse)(nil),          // 1: analysis.FeeResponse
	(*UpdateConfigRequest)(nil),  // 2: analysis.UpdateConfigRequest
	(*FeeConfigResponse)(nil),    // 3: analysis.FeeConfigResponse
	(*GetConfigRequest)(nil),     // 4: analysis.GetConfigRequest
	(*RecordProfitRequest)(nil),  // 5: analysis.RecordProfitRequest
	(*RecordProfitResponse)(nil), // 6: analysis.RecordProfitResponse
	(*TopEntity)(nil),            // 7: analysis.TopEntity
	(*AnalyticsResponse)(nil),    // 8: analysis.AnalyticsResponse
	(*GetAnalyticsRequest)(nil),  // 9: analysis.GetAnalyticsRequest
	(*GetHistoryRequest)(nil),    // 10: analysis.GetHistoryRequest
	(*ProfitLogItem)(nil),        // 11: analysis.ProfitLogItem
	(*HistoryResponse)(nil),      // 12: analysis.HistoryResponse
}
var file_analysis_proto_analysis_proto_depIdxs = []int32{
	7,  // 0: analysis.AnalyticsResponse.topRestaurants:type_name -> analysis.TopEntity
	7,  // 1: analysis.AnalyticsResponse.topUsers:type_name -> analysis.TopEntity
	11, // 2: analysis.HistoryResponse.logs:type_name -> analysis.ProfitLogItem
	0,  // 3: analysis.AnalysisService.CalculateFees:input_type -> analysis.CalculationRequest
	2,  // 4: analysis.AnalysisService.UpdateFeeConfiguration:input_type -> analysis.UpdateConfigRequest
	4,  // 5: analysis.AnalysisService.GetCurrentConfig:input_type -> analysis.GetConfigRequest
	5,  // 6: analysis.AnalysisService.RecordOrderProfit:input_type -> analysis.RecordProfitRequest
	9,  // 7: analysis.AnalysisService.GetAnalytics:input_type -> analysis.GetAnalyticsRequest
	10, // 8: analysis.AnalysisService.GetProfitHistory:input_type -> analysis.GetHistoryRequest
	1,  // 9: analysis.AnalysisService.CalculateFees:output_type -> analysis.FeeResponse
	3,  // 10: analysis.AnalysisService.UpdateFeeConfiguration:output_type -> analysis.FeeConfigResponse
	3,  // 11: analysis.AnalysisService.GetCurrentConfig:output_type -> analysis.FeeConfigResponse
	6,  // 12: analysis.AnalysisService.RecordOrderProfit:output_type -> analysis.RecordProfitResponse
	8,  // 13: analysis.AnalysisService.GetAnalytics:output_type -> analysis.AnalyticsResponse
	12, // 14: analysis.AnalysisService.GetProfitHistory:output_type -> analysis.HistoryResponse
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_analysis_proto_analysis_proto_init() }
func file_analysis_proto_analysis_proto_init() {
	if File_analysis_proto_analysis_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_analysis_proto_analysis_proto_rawDesc), len(file_analysis_proto_analysis_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_analysis_proto_analysis_proto_goTypes,
		DependencyIndexes: file_analysis_proto_analysis_proto_depIdxs,
		MessageInfos:      file_analysis_proto_analysis_proto_msgTypes,
	}.Build()
	File_analysis_proto_analysis_proto = out.File
	file_analysis_proto_analysis_proto_goTypes = nil
	file_analysis_proto_analysis_proto_depIdxs = nil
}
