// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: stakeholders/proto/stakeholders.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StakeholdersService_CreateCustomer_FullMethodName       = "/stakeholders.StakeholdersService/CreateCustomer"
	StakeholdersService_GetCustomer_FullMethodName          = "/stakeholders.StakeholdersService/GetCustomer"
	StakeholdersService_CreateDeliveryPerson_FullMethodName = "/stakeholders.StakeholdersService/CreateDeliveryPerson"
	StakeholdersService_GetDeliveryPerson_FullMethodName    = "/stakeholders.StakeholdersService/GetDeliveryPerson"
	StakeholdersService_UpdateWorkingStatus_FullMethodName  = "/stakeholders.StakeholdersService/UpdateWorkingStatus"
)

// StakeholdersServiceClient is the client API for StakeholdersService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StakeholdersServiceClient interface {
	// --- CUSTOMER ENDPOINTS ---
	CreateCustomer(ctx context.Context, in *CreateCustomerRequest, opts ...grpc.CallOption) (*CustomerResponse, error)
	GetCustomer(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*CustomerResponse, error)
	// --- DELIVERY PERSON ENDPOINTS ---
	CreateDeliveryPerson(ctx context.Context, in *CreateDeliveryPersonRequest, opts ...grpc.CallOption) (*DeliveryPersonResponse, error)
	GetDeliveryPerson(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*DeliveryPersonResponse, error)
	UpdateWorkingStatus(ctx context.Context, in *UpdateWorkStatusRequest, opts ...grpc.CallOption) (*DeliveryPersonResponse, error)
}

type stakeholdersServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStakeholdersServiceClient(cc grpc.ClientConnInterface) StakeholdersServiceClient {
	return &stakeholdersServiceClient{cc}
}

func (c *stakeholdersServiceClient) CreateCustomer(ctx context.Context, in *CreateCustomerRequest, opts ...grpc.CallOption) (*CustomerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CustomerResponse)
	err := c.cc.Invoke(ctx, StakeholdersService_CreateCustomer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stakeholdersServiceClient) GetCustomer(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*CustomerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CustomerResponse)
	err := c.cc.Invoke(ctx, StakeholdersService_GetCustomer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stakeholdersServiceClient) CreateDeliveryPerson(ctx context.Context, in *CreateDeliveryPersonRequest, opts ...grpc.CallOption) (*DeliveryPersonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeliveryPersonResponse)
	err := c.cc.Invoke(ctx, StakeholdersService_CreateDeliveryPerson_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stakeholdersServiceClient) GetDeliveryPerson(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*DeliveryPersonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeliveryPersonResponse)
	err := c.cc.Invoke(ctx, StakeholdersService_GetDeliveryPerson_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stakeholdersServiceClient) UpdateWorkingStatus(ctx context.Context, in *UpdateWorkStatusRequest, opts ...grpc.CallOption) (*DeliveryPersonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeliveryPersonResponse)
	err := c.cc.Invoke(ctx, StakeholdersService_UpdateWorkingStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StakeholdersServiceServer is the server API for StakeholdersService service.
// All implementations must embed UnimplementedStakeholdersServiceServer
// for forward compatibility.
type StakeholdersServiceServer interface {
	// --- CUSTOMER ENDPOINTS ---
	CreateCustomer(context.Context, *CreateCustomerRequest) (*CustomerResponse, error)
	GetCustomer(context.Context, *GetRequest) (*CustomerResponse, error)
	// --- DELIVERY PERSON ENDPOINTS ---
	CreateDeliveryPerson(context.Context, *CreateDeliveryPersonRequest) (*DeliveryPersonResponse, error)
	GetDeliveryPerson(context.Context, *GetRequest) (*DeliveryPersonResponse, error)
	UpdateWorkingStatus(context.Context, *UpdateWorkStatusRequest) (*DeliveryPersonResponse, error)
	mustEmbedUnimplementedStakeholdersServiceServer()
}

// UnimplementedStakeholdersServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStakeholdersServiceServer struct{}

func (UnimplementedStakeholdersServiceServer) CreateCustomer(context.Context, *CreateCustomerRequest) (*CustomerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCustomer not implemented")
}
func (UnimplementedStakeholdersServiceServer) GetCustomer(context.Context, *GetRequest) (*CustomerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCustomer not implemented")
}
func (UnimplementedStakeholdersServiceServer) CreateDeliveryPerson(context.Context, *CreateDeliveryPersonRequest) (*DeliveryPersonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDeliveryPerson not implemented")
}
func (UnimplementedStakeholdersServiceServer) GetDeliveryPerson(context.Context, *GetRequest) (*DeliveryPersonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeliveryPerson not implemented")
}
func (UnimplementedStakeholdersServiceServer) UpdateWorkingStatus(context.Context, *UpdateWorkStatusRequest) (*DeliveryPersonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateWorkingStatus not implemented")
}
func (UnimplementedStakeholdersServiceServer) mustEmbedUnimplementedStakeholdersServiceServer() {}
func (UnimplementedStakeholdersServiceServer) testEmbeddedByValue()                             {}

// UnsafeStakeholdersServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StakeholdersServiceServer will
// result in compilation errors.
type UnsafeStakeholdersServiceServer interface {
	mustEmbedUnimplementedStakeholdersServiceServer()
}

func RegisterStakeholdersServiceServer(s grpc.ServiceRegistrar, srv StakeholdersServiceServer) {
	// If the following call pancis, it indicates UnimplementedStakeholdersServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StakeholdersService_ServiceDesc, srv)
}

func _StakeholdersService_CreateCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCustomerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StakeholdersServiceServer).CreateCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StakeholdersService_CreateCustomer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StakeholdersServiceServer).CreateCustomer(ctx, req.(*CreateCustomerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StakeholdersService_GetCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StakeholdersServiceServer).GetCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StakeholdersService_GetCustomer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StakeholdersServiceServer).GetCustomer(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StakeholdersService_CreateDeliveryPerson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDeliveryPersonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StakeholdersServiceServer).CreateDeliveryPerson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StakeholdersService_CreateDeliveryPerson_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StakeholdersServiceServer).CreateDeliveryPerson(ctx, req.(*CreateDeliveryPersonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StakeholdersService_GetDeliveryPerson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StakeholdersServiceServer).GetDeliveryPerson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StakeholdersService_GetDeliveryPerson_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StakeholdersServiceServer).GetDeliveryPerson(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StakeholdersService_UpdateWorkingStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateWorkStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StakeholdersServiceServer).UpdateWorkingStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StakeholdersService_UpdateWorkingStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StakeholdersServiceServer).UpdateWorkingStatus(ctx, req.(*UpdateWorkStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StakeholdersService_ServiceDesc is the grpc.ServiceDesc for StakeholdersService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StakeholdersService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stakeholders.StakeholdersService",
	HandlerType: (*StakeholdersServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCustomer",
			Handler:    _StakeholdersService_CreateCustomer_Handler,
		},
		{
			MethodName: "GetCustomer",
			Handler:    _StakeholdersService_GetCustomer_Handler,
		},
		{
			MethodName: "CreateDeliveryPerson",
			Handler:    _StakeholdersService_CreateDeliveryPerson_Handler,
		},
		{
			MethodName: "GetDeliveryPerson",
			Handler:    _StakeholdersService_GetDeliveryPerson_Handler,
		},
		{
			MethodName: "UpdateWorkingStatus",
			Handler:    _StakeholdersService_UpdateWorkingStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stakeholders/proto/stakeholders.proto",
}
