// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: stakeholders/proto/stakeholders.proto

package proto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --- ENUMS ---
type VehicleType int32

const (
	VehicleType_NO_VEHICLE VehicleType = 0
	VehicleType_CAR        VehicleType = 1
	VehicleType_BIKE       VehicleType = 2
	VehicleType_SCOOTER    VehicleType = 3
)

// Enum value maps for VehicleType.
var (
	VehicleType_name = map[int32]string{
		0: "NO_VEHICLE",
		1: "CAR",
		2: "BIKE",
		3: "SCOOTER",
	}
	VehicleType_value = map[string]int32{
		"NO_VEHICLE": 0,
		"CAR":        1,
		"BIKE":       2,
		"SCOOTER":    3,
	}
)

func (x VehicleType) Enum() *VehicleType {
	p := new(VehicleType)
	*p = x
	return p
}

func (x VehicleType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VehicleType) Descriptor() protoreflect.EnumDescriptor {
	return file_stakeholders_proto_stakeholders_proto_enumTypes[0].Descriptor()
}

func (VehicleType) Type() protoreflect.EnumType {
	return &file_stakeholders_proto_stakeholders_proto_enumTypes[0]
}

func (x VehicleType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VehicleType.Descriptor instead.
func (VehicleType) EnumDescriptor() ([]byte, []int) {
	return file_stakeholders_proto_stakeholders_proto_rawDescGZIP(), []int{0}
}

// --- SHARED ---
type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_stakeholders_proto_stakeholders_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stakeholders_proto_stakeholders_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_stakeholders_proto_stakeholders_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// --- CUSTOMER MESSAGES ---
type CreateCustomerRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	UserId    string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	FirstName string                 `protobuf:"bytes,2,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName  string                 `protobuf:"bytes,3,opt,name=lastName,proto3" json:"lastName,omitempty"`
	// Address info (Same as Restaurant)
	Address       string  `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Latitude      float64 `protobuf:"fixed64,5,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64 `protobuf:"fixed64,6,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCustomerRequest) Reset() {
	*x = CreateCustomerRequest{}
	mi := &file_stakeholders_proto_stakeholders_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCustomerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCustomerRequest) ProtoMessage() {}

func (x *CreateCustomerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stakeholders_proto_stakeholders_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCustomerRequest.ProtoReflect.Descriptor instead.
func (*CreateCustomerRequest) Descriptor() ([]byte, []int) {
	return file_stakeholders_proto_stakeholders_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCustomerRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateCustomerRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *CreateCustomerRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *CreateCustomerRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CreateCustomerRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *CreateCustomerRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type CustomerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Latitude      float64                `protobuf:"fixed64,5,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,6,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomerResponse) Reset() {
	*x = CustomerResponse{}
	mi := &file_stakeholders_proto_stakeholders_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerResponse) ProtoMessage() {}

func (x *CustomerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stakeholders_proto_stakeholders_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerResponse.ProtoReflect.Descriptor instead.
func (*CustomerResponse) Descriptor() ([]byte, []int) {
	return file_stakeholders_proto_stakeholders_proto_rawDescGZIP(), []int{2}
}

func (x *CustomerResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CustomerResponse) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *CustomerResponse) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *CustomerResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CustomerResponse) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *CustomerResponse) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

// --- DELIVERY PERSON MESSAGES ---
type CreateDeliveryPersonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Vehicle       VehicleType            `protobuf:"varint,4,opt,name=vehicle,proto3,enum=stakeholders.VehicleType" json:"vehicle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDeliveryPersonRequest) Reset() {
	*x = CreateDeliveryPersonRequest{}
	mi := &file_stakeholders_proto_stakeholders_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDeliveryPersonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDeliveryPersonRequest) ProtoMessage() {}

func (x *CreateDeliveryPersonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stakeholders_proto_stakeholders_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDeliveryPersonRequest.ProtoReflect.Descriptor instead.
func (*CreateDeliveryPersonRequest) Descriptor() ([]byte, []int) {
	return file_stakeholders_proto_stakeholders_proto_rawDescGZIP(), []int{3}
}

func (x *CreateDeliveryPersonRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateDeliveryPersonRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *CreateDeliveryPersonRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *CreateDeliveryPersonRequest) GetVehicle() VehicleType {
	if x != nil {
		return x.Vehicle
	}
	return VehicleType_NO_VEHICLE
}

type UpdateWorkStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	IsWorking     bool                   `protobuf:"varint,2,opt,name=isWorking,proto3" json:"isWorking,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWorkStatusRequest) Reset() {
	*x = UpdateWorkStatusRequest{}
	mi := &file_stakeholders_proto_stakeholders_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWorkStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWorkStatusRequest) ProtoMessage() {}

func (x *UpdateWorkStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stakeholders_proto_stakeholders_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWorkStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateWorkStatusRequest) Descriptor() ([]byte, []int) {
	return file_stakeholders_proto_stakeholders_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateWorkStatusRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateWorkStatusRequest) GetIsWorking() bool {
	if x != nil {
		return x.IsWorking
	}
	return false
}

type DeliveryPersonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Vehicle       VehicleType            `protobuf:"varint,4,opt,name=vehicle,proto3,enum=stakeholders.VehicleType" json:"vehicle,omitempty"`
	IsWorking     bool                   `protobuf:"varint,5,opt,name=isWorking,proto3" json:"isWorking,omitempty"`
	DeliveryCount int32                  `protobuf:"varint,6,opt,name=deliveryCount,proto3" json:"deliveryCount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveryPersonResponse) Reset() {
	*x = DeliveryPersonResponse{}
	mi := &file_stakeholders_proto_stakeholders_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryPersonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryPersonResponse) ProtoMessage() {}

func (x *DeliveryPersonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stakeholders_proto_stakeholders_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryPersonResponse.ProtoReflect.Descriptor instead.
func (*DeliveryPersonResponse) Descriptor() ([]byte, []int) {
	return file_stakeholders_proto_stakeholders_proto_rawDescGZIP(), []int{5}
}

func (x *DeliveryPersonResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeliveryPersonResponse) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *DeliveryPersonResponse) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *DeliveryPersonResponse) GetVehicle() VehicleType {
	if x != nil {
		return x.Vehicle
	}
	return VehicleType_NO_VEHICLE
}

func (x *DeliveryPersonResponse) GetIsWorking() bool {
	if x != nil {
		return x.IsWorking
	}
	return false
}

func (x *DeliveryPersonResponse) GetDeliveryCount() int32 {
	if x != nil {
		return x.DeliveryCount
	}
	return 0
}

var File_stakeholders_proto_stakeholders_proto protoreflect.FileDescriptor

const file_stakeholders_proto_stakeholders_proto_rawDesc = "" +
	"\n" +
	"%stakeholders/proto/stakeholders.proto\x12\fstakeholders\x1a\x1cgoogle/api/annotations.proto\"$\n" +
	"\n" +
	"GetRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\"\xbd\x01\n" +
	"\x15CreateCustomerRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x1c\n" +
	"\tfirstName\x18\x02 \x01(\tR\tfirstName\x12\x1a\n" +
	"\blastName\x18\x03 \x01(\tR\blastName\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12\x1a\n" +
	"\blatitude\x18\x05 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x06 \x01(\x01R\tlongitude\"\xb8\x01\n" +
	"\x10CustomerResponse\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x1c\n" +
	"\tfirstName\x18\x02 \x01(\tR\tfirstName\x12\x1a\n" +
	"\blastName\x18\x03 \x01(\tR\blastName\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12\x1a\n" +
	"\blatitude\x18\x05 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x06 \x01(\x01R\tlongitude\"\xa4\x01\n" +
	"\x1bCreateDeliveryPersonRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x1c\n" +
	"\tfirstName\x18\x02 \x01(\tR\tfirstName\x12\x1a\n" +
	"\blastName\x18\x03 \x01(\tR\blastName\x123\n" +
	"\avehicle\x18\x04 \x01(\x0e2\x19.stakeholders.VehicleTypeR\avehicle\"O\n" +
	"\x17UpdateWorkStatusRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x1c\n" +
	"\tisWorking\x18\x02 \x01(\bR\tisWorking\"\xe3\x01\n" +
	"\x16DeliveryPersonResponse\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x1c\n" +
	"\tfirstName\x18\x02 \x01(\tR\tfirstName\x12\x1a\n" +
	"\blastName\x18\x03 \x01(\tR\blastName\x123\n" +
	"\avehicle\x18\x04 \x01(\x0e2\x19.stakeholders.VehicleTypeR\avehicle\x12\x1c\n" +
	"\tisWorking\x18\x05 \x01(\bR\tisWorking\x12$\n" +
	"\rdeliveryCount\x18\x06 \x01(\x05R\rdeliveryCount*=\n" +
	"\vVehicleType\x12\x0e\n" +
	"\n" +
	"NO_VEHICLE\x10\x00\x12\a\n" +
	"\x03CAR\x10\x01\x12\b\n" +
	"\x04BIKE\x10\x02\x12\v\n" +
	"\aSCOOTER\x10\x032\xb1\x05\n" +
	"\x13StakeholdersService\x12x\n" +
	"\x0eCreateCustomer\x12#.stakeholders.CreateCustomerRequest\x1a\x1e.stakeholders.CustomerResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/stakeholders/customer\x12p\n" +
	"\vGetCustomer\x12\x18.stakeholders.GetRequest\x1a\x1e.stakeholders.CustomerResponse\"'\x82\xd3\xe4\x93\x02!\x12\x1f/stakeholders/customer/{userId}\x12\x91\x01\n" +
	"\x14CreateDeliveryPerson\x12).stakeholders.CreateDeliveryPersonRequest\x1a$.stakeholders.DeliveryPersonResponse\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/stakeholders/delivery-person\x12\x83\x01\n" +
	"\x11GetDeliveryPerson\x12\x18.stakeholders.GetRequest\x1a$.stakeholders.DeliveryPersonResponse\".\x82\xd3\xe4\x93\x02(\x12&/stakeholders/delivery-person/{userId}\x12\x93\x01\n" +
	"\x13UpdateWorkingStatus\x12%.stakeholders.UpdateWorkStatusRequest\x1a$.stakeholders.DeliveryPersonResponse\"/\x82\xd3\xe4\x93\x02):\x01*\x1a$/stakeholders/delivery-person/statusB\x1cZ\x1a/COMMON/stakeholders/protob\x06proto3"

var (
	file_stakeholders_proto_stakeholders_proto_rawDescOnce sync.Once
	file_stakeholders_proto_stakeholders_proto_rawDescData []byte
)

func file_stakeholders_proto_stakeholders_proto_rawDescGZIP() []byte {
	file_stakeholders_proto_stakeholders_proto_rawDescOnce.Do(func() {
		file_stakeholders_proto_stakeholders_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stakeholders_proto_stakeholders_proto_rawDesc), len(file_stakeholders_proto_stakeholders_proto_rawDesc)))
	})
	return file_stakeholders_proto_stakeholders_proto_rawDescData
}

var file_stakeholders_proto_stakeholders_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_stakeholders_proto_stakeholders_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_stakeholders_proto_stakeholders_proto_goTypes = []any{
	(VehicleType)(0),                    // 0: stakeholders.VehicleType
	(*GetRequest)(nil),                  // 1: stakeholders.GetRequest
	(*CreateCustomerRequest)(nil),       // 2: stakeholders.CreateCustomerRequest
	(*CustomerResponse)(nil),            // 3: stakeholders.CustomerResponse
	(*CreateDeliveryPersonRequest)(nil), // 4: stakeholders.CreateDeliveryPersonRequest
	(*UpdateWorkStatusRequest)(nil),     // 5: stakeholders.UpdateWorkStatusRequest
	(*DeliveryPersonResponse)(nil),      // 6: stakeholders.DeliveryPersonResponse
}
var file_stakeholders_proto_stakeholders_proto_depIdxs = []int32{
	0, // 0: stakeholders.CreateDeliveryPersonRequest.vehicle:type_name -> stakeholders.VehicleType
	0, // 1: stakeholders.DeliveryPersonResponse.vehicle:type_name -> stakeholders.VehicleType
	2, // 2: stakeholders.StakeholdersService.CreateCustomer:input_type -> stakeholders.CreateCustomerRequest
	1, // 3: stakeholders.StakeholdersService.GetCustomer:input_type -> stakeholders.GetRequest
	4, // 4: stakeholders.StakeholdersService.CreateDeliveryPerson:input_type -> stakeholders.CreateDeliveryPersonRequest
	1, // 5: stakeholders.StakeholdersService.GetDeliveryPerson:input_type -> stakeholders.GetRequest
	5, // 6: stakeholders.StakeholdersService.UpdateWorkingStatus:input_type -> stakeholders.UpdateWorkStatusRequest
	3, // 7: stakeholders.StakeholdersService.CreateCustomer:output_type -> stakeholders.CustomerResponse
	3, // 8: stakeholders.StakeholdersService.GetCustomer:output_type -> stakeholders.CustomerResponse
	6, // 9: stakeholders.StakeholdersService.CreateDeliveryPerson:output_type -> stakeholders.DeliveryPersonResponse
	6, // 10: stakeholders.StakeholdersService.GetDeliveryPerson:output_type -> stakeholders.DeliveryPersonResponse
	6, // 11: stakeholders.StakeholdersService.UpdateWorkingStatus:output_type -> stakeholders.DeliveryPersonResponse
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_stakeholders_proto_stakeholders_proto_init() }
func file_stakeholders_proto_stakeholders_proto_init() {
	if File_stakeholders_proto_stakeholders_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stakeholders_proto_stakeholders_proto_rawDesc), len(file_stakeholders_proto_stakeholders_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stakeholders_proto_stakeholders_proto_goTypes,
		DependencyIndexes: file_stakeholders_proto_stakeholders_proto_depIdxs,
		EnumInfos:         file_stakeholders_proto_stakeholders_proto_enumTypes,
		MessageInfos:      file_stakeholders_proto_stakeholders_proto_msgTypes,
	}.Build()
	File_stakeholders_proto_stakeholders_proto = out.File
	file_stakeholders_proto_stakeholders_proto_goTypes = nil
	file_stakeholders_proto_stakeholders_proto_depIdxs = nil
}
